<template lang="pug">
  .scg.
    <svg viewBox="0 0 1500 844" xmlns:xlink="http://www.w3.org/1999/xlink" role="img" aria-label="6 Marketing Questions">
            <g font-family="Open Sans, sans-serif">
            <rect x="0" y="0" width="1500" height="844" fill="#ffffff"></rect>
            <text x="47.8" y="86.1" font-size="50.0" fill="#002b64" textLength="726.3" lengthAdjust="spacing">(6) Critical Marketing Questions</text>
            <circle cx="57.8" cy="144.0" r="2.60" fill="#434343"></circle>
            <text x="80.1" y="149.6" font-size="18.8" fill="#002b64" font-weight="700" textLength="216.5" lengthAdjust="spacing">Who are you targeting?</text>
            <text x="125.9" y="200.7" font-size="18.8" fill="#434343" textLength="756.2" lengthAdjust="spacing">(What is the profile of your ideal customer? – How would you describe them to others?)</text>
            <circle cx="57.8" cy="245.0" r="2.60" fill="#002b64"></circle>
            <text x="80.1" y="250.7" font-size="18.8" fill="#002b64" font-weight="700" textLength="455.5" lengthAdjust="spacing">What are their key concerns/common problems?</text>
            <text x="125.9" y="300.7" font-size="18.8" fill="#434343" textLength="709.6" lengthAdjust="spacing">(From their perspective (not yours) why do they seek a solution to their problem?)</text>
            <circle cx="57.8" cy="345.0" r="2.60" fill="#002b64"></circle>
            <text x="80.1" y="350.7" font-size="18.8" fill="#002b64" font-weight="700" textLength="465.9" lengthAdjust="spacing">What are their legitimate purchasing constraints?</text>
            <text x="125.9" y="400.7" font-size="18.8" fill="#434343" textLength="551.1" lengthAdjust="spacing">(What stops them from paying for an answer to their problem?)</text>
            <circle cx="57.8" cy="445.0" r="2.60" fill="#434343"></circle>
            <text x="80.1" y="450.7" font-size="18.8" fill="#002b64" font-weight="700" textLength="233.5" lengthAdjust="spacing">What makes you special?</text>
            <text x="125.9" y="500.7" font-size="18.8" fill="#434343" textLength="1324.1" lengthAdjust="spacing">(How can you solve your customer’s problems easier than your competition? How do you reduce risk, improve convenience, provide greater certainty of</text>
            <text x="107.2" y="534.0" font-size="18.8" fill="#434343" textLength="313.7" lengthAdjust="spacing">outcomes or save money for them?)</text>
            <circle cx="57.8" cy="579.4" r="2.60" fill="#002b64"></circle>
            <text x="80.1" y="585.0" font-size="18.8" fill="#002b64" font-weight="700" textLength="423.5" lengthAdjust="spacing">How do you add value to your target market?</text>
            <text x="125.9" y="635.0" font-size="18.8" fill="#434343" textLength="714.9" lengthAdjust="spacing">(What do you DO for them?  Does your promise ‘speak your customers language’?)</text>
            <circle cx="57.8" cy="679.4" r="2.60" fill="#002b64"></circle>
            <text x="80.1" y="685.0" font-size="18.8" fill="#002b64" font-weight="700" textLength="710.3" lengthAdjust="spacing">What are the message channels that you can use to promote your business?</text>
            <text x="125.9" y="735.0" font-size="18.8" fill="#434343" textLength="838.4" lengthAdjust="spacing">(Does your target customer respond to social media, hard copy media, mainstream advertising?)</text>
            </g>
            <g class="firm-mark">
              <circle class="fm-disc" cx="125" cy="800" r="22" :fill="firmColour"></circle>
              <text class="fm-init" x="125" y="808" text-anchor="middle" fill="#fff"
                    font-family="Open Sans, sans-serif" font-size="20" font-weight="700">{{ firmInitial }}</text>
              <text class="fm-name" x="159" y="807" fill="#002B64"
                    font-family="Open Sans, sans-serif" font-size="21" font-weight="600">{{ firmName }}</text>
            </g>
          </svg>
</template>

<script>
/**
 * ⚠ GENERATED — DO NOT EDIT THIS FILE.
 *
 * Lifted from design/mockups/strategy-concept-batch-5.html (drawing 2) by
 * `node scripts/build-concept-graphics.js`. Correct the drawing and run the
 * script; an edit made here is lost and breaks the guarantee that what ships is
 * what Mike approved.
 *
 * Vue 2, Options API, Pug.
 */
export default {
  name: 'Concept6MarketingQuestions',

  props: {
    /** The advisor firm's name, printed beside the mark. */
    firmName: {
      type: String,
      default: ''
    },

    /** One letter for the disc. */
    firmInitial: {
      type: String,
      default: ''
    },

    /** The firm's colour, as a CSS colour. */
    firmColour: {
      type: String,
      default: '#0070c0'
    }
  }
}
</script>

<style scoped>
.scg {
  width: 100%;
}

.scg >>> svg {
  display: block;
  width: 100%;
  height: auto;
}
</style>
