<template lang="pug">
  .scg.
    <svg viewBox="0 0 1500 844" xmlns:xlink="http://www.w3.org/1999/xlink" role="img" aria-label="(Inbound) Landing Page Review">
            <g font-family="Open Sans, sans-serif">
            <rect x="0" y="0" width="1500" height="844" fill="#ffffff"></rect>
            <text x="56.9" y="93.1" font-size="50.0" fill="#002b64" textLength="673.8" lengthAdjust="spacing">Designing Your Landing Page</text>
            <text x="56.9" y="174.4" font-size="20.8" fill="#434343" textLength="1373.1" lengthAdjust="spacing">OK, you’ve done all the hard work of defining your customer, clarifying their needs, reducing sales friction points (by improving your product</text>
            <text x="56.9" y="203.0" font-size="20.8" fill="#434343" textLength="1373.3" lengthAdjust="spacing">or service) and building powerful, well placed, outbound messages. Congratulations, it worked!  You now have potential customers</text>
            <text x="56.9" y="231.1" font-size="20.8" fill="#434343" textLength="1189.8" lengthAdjust="spacing">(prospects) ‘clicking the links’ or visiting your landing page; all you have to do now is figure out what you want them to see…</text>
            <text x="56.9" y="321.2" font-size="20.8" fill="#434343" textLength="1373.3" lengthAdjust="spacing">The following 4 slides help you define the purpose of each section on your landing page. (Each section could be defined as a colour ‘band’ or</text>
            <text x="56.9" y="349.9" font-size="20.8" fill="#434343" textLength="762.2" lengthAdjust="spacing">could simply be defined by a Title, Graphic or ‘Widget’ - such as a sign up form.)</text>
            <text x="56.9" y="440.0" font-size="20.8" fill="#434343" textLength="1373.6" lengthAdjust="spacing">Before you start laying up text and graphics, determine the objective (of each section) in relation to the psychology of the sale and put it in</text>
            <text x="56.9" y="468.6" font-size="20.8" fill="#434343" textLength="1373.4" lengthAdjust="spacing">‘plain english’ terms of what you believe your target customer is thinking, and the ‘logic’ of what you were hoping to achieve. From there, you</text>
            <text x="56.9" y="496.8" font-size="20.8" fill="#434343" textLength="386.0" lengthAdjust="spacing">can then add the words and images etc.</text>
            <text x="56.9" y="586.9" font-size="20.8" fill="#434343" textLength="756.3" lengthAdjust="spacing">The advantage of doing it this way is that in future, you can review the logic of</text>
            <text x="820.5" y="586.9" font-size="20.8" fill="#002b64" textLength="585.0" lengthAdjust="spacing">‘what did we think our target customer wanted to see/read’?</text>
            <text x="1411.8" y="586.9" font-size="20.8" fill="#434343">vs</text>
            <text x="56.9" y="615.5" font-size="20.8" fill="#002b64" textLength="261.1" lengthAdjust="spacing">‘what we said in response’?</text>
            <text x="324.4" y="615.5" font-size="20.8" fill="#434343" textLength="1112.4" lengthAdjust="spacing">You can test this by simply talking with friends, family, existing customers etc because you can ask in ‘plain english’</text>
            <text x="56.9" y="643.6" font-size="20.8" fill="#434343" textLength="78.4" lengthAdjust="spacing">terms…</text>
            <text x="135.9" y="643.6" font-size="20.8" fill="#434343" font-style="italic" textLength="1294.3" lengthAdjust="spacing">“If you went to a site like this, what would you want to know in the first 10 secs of reading, - if you liked what you saw, what would it take for</text>
            <text x="56.9" y="671.8" font-size="20.8" fill="#434343" font-style="italic" textLength="656.1" lengthAdjust="spacing">you to agree to click subscribe/ sign up for a demo/ agree to purchase?”</text>
            <text x="719.3" y="671.8" font-size="20.8" fill="#434343" textLength="111.4" lengthAdjust="spacing">and so on...</text>
            </g>
            <g class="firm-mark">
              <circle class="fm-disc" cx="125" cy="800" r="22" :fill="firmColour"></circle>
              <text class="fm-init" x="125" y="808" text-anchor="middle" fill="#fff"
                    font-family="Open Sans, sans-serif" font-size="20" font-weight="700">{{ firmInitial }}</text>
              <text class="fm-name" x="159" y="807" fill="#002B64"
                    font-family="Open Sans, sans-serif" font-size="21" font-weight="600">{{ firmName }}</text>
            </g>
          </svg>
</template>

<script>
/**
 * ⚠ GENERATED — DO NOT EDIT THIS FILE.
 *
 * Lifted from design/mockups/strategy-concept-batch-5.html (drawing 6) by
 * `node scripts/build-concept-graphics.js`. Correct the drawing and run the
 * script; an edit made here is lost and breaks the guarantee that what ships is
 * what Mike approved.
 *
 * Vue 2, Options API, Pug.
 */
export default {
  name: 'ConceptInboundLandingPageReview',

  props: {
    /** The advisor firm's name, printed beside the mark. */
    firmName: {
      type: String,
      default: ''
    },

    /** One letter for the disc. */
    firmInitial: {
      type: String,
      default: ''
    },

    /** The firm's colour, as a CSS colour. */
    firmColour: {
      type: String,
      default: '#0070c0'
    }
  }
}
</script>

<style scoped>
.scg {
  width: 100%;
}

.scg >>> svg {
  display: block;
  width: 100%;
  height: auto;
}
</style>
