<template lang="pug">
  .scg.
    <svg viewBox="0 0 1500 844" role="img"
               aria-label="Risk Reward Matrix: four quadrants pairing existing or new market with existing or new product, risk increasing to the right and upward.">
            <rect width="1500" height="844" fill="#fff"></rect>
            <text x="55.9" y="97.2" font-family="Open Sans, sans-serif" font-size="50" fill="#002B64">Risk Reward Matrix</text>

            <!-- Quadrants: x249.5/749.5, y161.2/420.6, each 500 x 259.4 -->
            <rect x="249.5" y="161.2" width="500" height="259.4" fill="#595959"></rect>
            <rect x="749.5" y="161.2" width="500" height="259.4" fill="#F92B2B"></rect>
            <rect x="249.5" y="420.6" width="500" height="259.4" fill="#A8D08C"></rect>
            <rect x="749.5" y="420.6" width="500" height="259.4" fill="#595959"></rect>

            <g font-family="Open Sans, sans-serif" font-size="43.8" font-weight="700">
              <text x="328.7" y="262.6" fill="#00FFFF">Existing Market</text>
              <text x="358.2" y="315.8" fill="#CCCCCC">New Product</text>
              <text x="864.6" y="279.8" fill="#FFFFFF">New Market</text>
              <text x="858.2" y="332.9" fill="#FFFFFF">New Product</text>
              <text x="328.7" y="539.2" fill="#262626">Existing Market</text>
              <text x="322.3" y="592.4" fill="#262626">Existing Product</text>
              <text x="864.6" y="522.0" fill="#00FFFF">New Market</text>
              <text x="822.3" y="575.2" fill="#CCCCCC">Existing Product</text>
            </g>

            <g font-family="Open Sans, sans-serif" font-size="29.2" fill="#002B64">
              <text x="174.9" y="599.7" transform="rotate(-90 174.9 599.7)">Risk becoming greater... &gt;</text>
              <text x="563.8" y="737.7">Risk becoming greater... &gt;</text>
            </g>

            <g class="firm-mark" transform="translate(0,0)">
              <circle class="fm-disc" cx="110" cy="790" r="24" :fill="firmColour"></circle>
              <text class="fm-init" x="110" y="799" text-anchor="middle" fill="#fff"
                    font-family="Open Sans, sans-serif" font-size="22" font-weight="700">{{ firmInitial }}</text>
              <text class="fm-name" x="146" y="798" fill="#002B64"
                    font-family="Open Sans, sans-serif" font-size="22.9" font-weight="600">{{ firmName }}</text>
            </g>
          </svg>
</template>

<script>
/**
 * ⚠ GENERATED — DO NOT EDIT THIS FILE.
 *
 * Lifted from design/mockups/strategy-concept-batch-1.html (drawing 1) by
 * `node scripts/build-concept-graphics.js`. Correct the drawing and run the
 * script; an edit made here is lost and breaks the guarantee that what ships is
 * what Mike approved.
 *
 * Vue 2, Options API, Pug.
 */
export default {
  name: 'RiskRewardMatrix',

  props: {
    /** The advisor firm's name, printed beside the mark. */
    firmName: {
      type: String,
      default: ''
    },

    /** One letter for the disc. */
    firmInitial: {
      type: String,
      default: ''
    },

    /** The firm's colour, as a CSS colour. */
    firmColour: {
      type: String,
      default: '#0070c0'
    }
  }
}
</script>

<style scoped>
.scg {
  width: 100%;
}

.scg >>> svg {
  display: block;
  width: 100%;
  height: auto;
}
</style>
