<template lang="pug">
  .scg.
    <svg viewBox="0 0 1500 844" role="img"
               aria-label="The 8 Profit Levers: three volume levers multiplied by two customer levers give Total Revenue, above three cost levers giving Total Expenses.">
            <rect width="1500" height="844" fill="#fff"></rect>
            <text x="55.9" y="91.3" font-family="Open Sans, sans-serif" font-size="50" fill="#002B64">The 8 Profit Levers</text>

            <g font-family="Open Sans, sans-serif" font-size="20.8" fill="#434343">
              <text x="47.9" y="175.0">Number of Foot-traffic</text>
              <text x="422.9" y="175.0">(Market Attention &#8211; Outbound Message Views)</text>
              <text x="47.9" y="213.6">Number of Prospects</text>
              <text x="422.9" y="213.6">(Shop Walk-ins / Phone-ins or Social &#8216;Click Thru&#8217;)</text>
              <text x="47.9" y="252.6">Number of Customers</text>
              <text x="422.9" y="252.6">(Percentage of Prospects that Become Customers)</text>
              <text x="47.9" y="360.1">Average Customer Spend</text>
              <text x="422.9" y="360.1">(Total Sales Value &#247; by Total Number of Transactions)</text>
              <text x="47.9" y="401.1">Average Customer Frequency</text>
              <text x="422.9" y="401.1">(How often do they buy per mth or year)</text>
              <text x="47.9" y="607.3">Sales Margin</text>
              <text x="422.9" y="607.3">(The Difference Between How Much You Sell It For minus What It Cost You)</text>
              <text x="47.9" y="646.4">Activity Driven Costs</text>
              <text x="422.9" y="646.4">(The Cost of Gaining A Customer)</text>
              <text x="47.9" y="685.5">Fixed Costs (Overheads)</text>
              <text x="422.9" y="685.5">(Total &lt;Regular&gt; Cost of &#8216;Being Open For Business&#8217; &#8211; Even When Nobody Buys)</text>
            </g>

            <!-- The operator and the two totals: 39.6pt bold. Reading only the first
                 span of each line had these at 20.8pt regular and grey. -->
            <text x="733.3" y="307.9" font-family="Open Sans, sans-serif" font-size="39.6"
                  font-weight="700" fill="#434343">X</text>
            <text x="591.9" y="490.7" font-family="Open Sans, sans-serif" font-size="39.6"
                  font-weight="700" fill="#002B64">= Total Revenue</text>
            <path d="M262.9 532.8 H1231.9" stroke="#002B64" stroke-width="4.2" fill="none"></path>
            <text x="583.5" y="779.8" font-family="Open Sans, sans-serif" font-size="39.6"
                  font-weight="700" fill="#002B64">= Total Expenses</text>

            <g class="firm-mark">

              <image class="fm-logo" x="88" y="784" width="240" height="44" preserveAspectRatio="xMinYMid meet" v-if="firmLogo" :href="firmLogo"></image>
              <circle class="fm-disc" cx="110" cy="806" r="22" v-if="!firmLogo" :fill="firmColour"></circle>
              <text class="fm-init" v-if="!firmLogo" x="110" y="814" text-anchor="middle" fill="#fff"
                    font-family="Open Sans, sans-serif" font-size="20" font-weight="700">{{ firmInitial }}</text>
              <text class="fm-name" v-if="!firmLogo" x="144" y="813" fill="#002B64"
                    font-family="Open Sans, sans-serif" font-size="21" font-weight="600">{{ firmName }}</text>
            </g>
            <rect class="firm-bar is-t" x="8.13" y="8.13" width="1483.74" height="14.8" :fill="firmColour"></rect>
            <rect class="firm-bar is-l" x="8.13" y="22.92" width="14.16" height="798.16" :fill="firmColour"></rect>
            <rect class="firm-bar is-r" x="1477.71" y="22.92" width="14.16" height="798.16" :fill="firmColour"></rect>
            <rect class="firm-bar is-bl" x="8.13" y="821.07" width="95.01" height="14.8" :fill="firmColour"></rect>
            <rect class="firm-bar is-brun" x="248.31" y="821.07" width="1243.56" height="14.8" :fill="firmColour"></rect>
          </svg>
</template>

<script>
/**
 * ⚠ GENERATED — DO NOT EDIT THIS FILE.
 *
 * Lifted from design/mockups/strategy-concept-batch-1.html (drawing 3) by
 * `node scripts/build-concept-graphics.js`. Correct the drawing and run the
 * script; an edit made here is lost and breaks the guarantee that what ships is
 * what Mike approved.
 *
 * Vue 2, Options API, Pug.
 */
export default {
  name: 'ConceptThe8ProfitLevers',

  props: {
    /** The advisor firm's name, printed beside the mark. */
    firmName: {
      type: String,
      default: ''
    },

    /** One letter for the disc. */
    firmInitial: {
      type: String,
      default: ''
    },

    /** The firm's colour, as a CSS colour. Brands the page border and the disc. */
    firmColour: {
      type: String,
      default: '#0070c0'
    },

    /**
     * The firm's real logo, as an absolute http(s) URL.
     *
     * Mike's ruling, 2026-09-22: this IS the mark. The initials disc and the
     * printed name are the fallback shown only when a firm holds no logo. The
     * box is a fixed height with preserveAspectRatio="xMinYMid meet", so a logo
     * of any proportion is scaled to fit and never stretched or cropped.
     *
     * Supplied by `firmBrand()` in server/utils/firmsDirectory.js, which reads
     * it from Advisor-e's own firm profile record and returns null for anything
     * that is not an http(s) URL — so an empty string here is the safe state,
     * not a missing value.
     */
    firmLogo: {
      type: String,
      default: ''
    }
  }
}
</script>

<style scoped>
.scg {
  width: 100%;
}

.scg >>> svg {
  display: block;
  width: 100%;
  height: auto;
}
</style>
