'use strict'

/**
 * @file The Org Chart Builder's record shape, its chart geometry and its checks.
 * @module utils/orgChart
 *
 * Approved artefact: `design/mockups/strategy-capture-org-chart-redrawn.html`, five decisions
 * ruled by Mike 2026-09-21 and approved to build from. Item 15.1, stage 5, capture form 3 of 9.
 * It supersedes `strategy-capture-parent-child-list.html`, which was approved and built the
 * same day and found wanting the moment he used it — see that row in `design/ARTEFACTS.md`.
 *
 * 🔴 ONE HOME, TWO SIDES. The keys below are a contract between the screen that writes
 * them and the save guard that admits them: a key shape written here and re-typed in
 * `server/utils/strategyOrgChart.js` would drift the first time either changed, and the
 * failure an advisor sees is "your typing could not be saved" with nothing to explain it.
 * The backend requires THIS file for the guard rather than holding a second copy, and
 * `tests/unit/orgChart.test.js` round-trips every key this module produces through it.
 *
 * 🔴 WHY THIS FORM HAS A SHAPE OF ITS OWN. Every other capture form saves a box by its
 * POSITION in Mike's table — table 0, row 5, column 3. His sheet has 30 numbered rows, so
 * an advisor adding role 31 would save to a position his document does not have and the
 * save would be REFUSED. His ruling, 2026-09-21: *"seeing as this needs to be dynamic —
 * perhaps it needs to be built like a 'mini-app' in order to function? … which is why the
 * original is in a spreadsheet"*.
 *
 * THE SHAPE:
 * - `orgroles` — the ordered roster of live role ids, comma separated. It says WHICH roles
 *   exist and in what order; anything not named in it is ignored on read.
 * - `orgrole-<n>-name` — the ROLE. A box, with the voice bar above it.
 * - `orgrole-<n>-person` — the person in it, and it may be empty.
 * - `orgrole-<n>-head` — the role this one reports to.
 *
 * 🔴 THE PERSON IS A THIRD KEY, NOT A SECOND HALF OF THE FIRST — Decision A of the redraw,
 * ruled 2026-09-21 after Mike used the two-column screen and found *"no ability to enter their
 * role which is critical in an organisational chart"*: he typed three people's names into the
 * only box there was, the one headed Role. A position and the person in it are two facts, and
 * two facts in one box cannot be left half-filled for a vacancy (Decision B) or reported on.
 *
 * 🔴 `reportsTo` NAMES A ROLE, NEVER A PERSON — Decision D, same day. His own sheet does that,
 * and a chart built on people breaks the moment somebody leaves.
 *
 * 🔴 ONE BOX, ONE KEY — BECAUSE THE VOICE BAR AND THE TIMELINE BOTH NEED ONE. The drawing
 * says every box on this screen carries the voice bar "unchanged", and Decision 11 of
 * 2026-09-16 apportions a recording's words by asking WHICH BOX was open when they were
 * said. Holding the whole chart in one entry would have kept the screen working and quietly
 * reduced that to a single field for thirty roles. The roster exists so that removing a role
 * needs no DELETE route: the id leaves the roster and its orphaned rows are never read.
 *
 * 🔴 `reportsTo` IS A NAME, NOT AN ID. His sheet's column holds a name, and his own worked
 * example puts `Shareholders` in it — which is NOT one of the 24 roles. An id could not
 * represent that at all, and the drawing requires it: Shareholders is drawn above the chart
 * as an outside parent rather than treated as an error.
 *
 * CommonJS, so the Restify backend can require it as well as the screen importing it.
 * No DOM, no window, nothing browser-only.
 */

/** The roster: which roles exist, and in what order. */
const ROSTER_KEY = 'orgroles'

/**
 * A ceiling on role ids and on the roster.
 *
 * His sheet has 30 numbered rows and the whole point of this form is that the 31st works.
 * 200 is far more than a chart a human reads in a session, and it bounds the key space so a
 * malformed or hostile body cannot invent unbounded rows in a client's plan.
 */
const MAX_ROLES = 200

/** `orgrole-12-name` / `-person` / `-head`, and nothing else. */
const ROLE_KEY = /^orgrole-([1-9][0-9]{0,2})-(name|person|head)$/

// ── the geometry, read off the approved drawing ──────────────────────────────
// Every number here is measured from
// `design/mockups/strategy-capture-org-chart-redrawn.html` section 4, whose chart was itself
// generated by THIS function from Org Chart.xlsx and only re-sized. They are not design
// choices made here and must not be "tidied": `tests/unit/orgChart.test.js` lays this
// module's output against that drawing's own 25 boxes and 24 connectors, coordinate by
// coordinate. The box grew from 152x38 to carry two lines — the role and the person in it.

/** One box, now two lines tall. */
const BOX_W = 176
const BOX_H = 52
/** Box to box across — 176 wide with a 16px gutter. */
const COL = 192
/** Level to level down — 52 tall with a 60px gap, which the elbow halves. */
const ROW = 112
/** Half the gap: a connector drops this far, crosses, then drops the same again. */
const ELBOW = 30
/** The role's baseline where a person sits beneath it, from the box's own top. */
const TEXT_ROLE = 22
/** The role's baseline where the box carries no person — it centres instead. */
const TEXT_ROLE_ALONE = 31
/** The person's baseline, beneath the role. */
const TEXT_PERSON = 39
/** The label sits on the box's centre line. */
const TEXT_MID = BOX_W / 2
/** Breathing room below the lowest box, so its border is not clipped by the viewBox. */
const PAD_BOTTOM = 8

/**
 * Is this a key the Org Chart Builder owns?
 *
 * The whitelist principle is unchanged from the positional guard — a key that is not one of
 * these three shapes, or whose id is out of range, is still refused.
 *
 * @param {string} key
 * @returns {boolean}
 */
function isOrgChartKey (key) {
  if (typeof key !== 'string') { return false }
  if (key === ROSTER_KEY) { return true }
  const m = ROLE_KEY.exec(key)
  return Boolean(m) && Number(m[1]) <= MAX_ROLES
}

/**
 * The key one role's box is saved under.
 *
 * @param {number} id the role's id, 1..MAX_ROLES
 * @param {'name'|'head'} part
 * @returns {string}
 */
function roleKey (id, part) {
  return 'orgrole-' + id + '-' + part
}

/**
 * The roles a session holds, in the roster's order.
 *
 * @param {Object.<string,string>} entries one concept's entries, keyed by field key
 * @returns {Array<{id: number, name: string, person: string, reportsTo: string}>}
 */
function rolesFrom (entries) {
  const held = entries || {}
  const raw = held[ROSTER_KEY]
  const roster = (raw === undefined || raw === null) ? '' : String(raw)
  const text = v => (v === undefined || v === null) ? '' : String(v)
  const seen = {}
  const out = []
  roster.split(',').forEach((part) => {
    const id = Number(String(part).trim())
    if (!Number.isInteger(id) || id < 1 || id > MAX_ROLES || seen[id]) { return }
    seen[id] = true
    out.push({
      id,
      name: text(held[roleKey(id, 'name')]),
      person: text(held[roleKey(id, 'person')]),
      reportsTo: text(held[roleKey(id, 'head')])
    })
  })
  return out
}

/**
 * The next free role id — above every id EVER used in this session, not merely every id
 * still on the roster.
 *
 * 🔴 IT READS THE ENTRIES, AND THE ROSTER ALONE IS NOT ENOUGH. Removing a role takes its id
 * off the roster and leaves `orgrole-<n>-name` where it is, by design — that is what makes a
 * DELETE route unnecessary. So a next id computed from the roster falls back the moment the
 * LAST role is removed, and the blank row the advisor then adds arrives holding the removed
 * person's name and their reporting line.
 *
 * Found by clicking the two buttons in a browser, in that order. The unit test that was
 * supposed to catch it removed a role from the MIDDLE of the list, where the highest id
 * survives and the fault cannot appear.
 *
 * @param {Array<{id: number}>} roles
 * @param {Object.<string,string>} [entries] the session's own entries, orphans included
 * @returns {number} 0 when the ceiling is reached
 */
function nextRoleId (roles, entries) {
  let top = 0
  const consider = (id) => { if (Number.isInteger(id) && id > top) { top = id } }
  ;(Array.isArray(roles) ? roles : []).forEach(r => consider(r.id))
  Object.keys(entries || {}).forEach((key) => {
    const m = ROLE_KEY.exec(key)
    if (m) { consider(Number(m[1])) }
  })
  return top < MAX_ROLES ? top + 1 : 0
}

/**
 * The entries that record a whole list of roles — the roster and every box that holds
 * something.
 *
 * Used when the advisor loads Mike's example or clears the list, which are the only two
 * moments this screen writes more than one box at a time.
 *
 * 🔴 AN EMPTY BOX IS NOT WRITTEN, AND THAT IS A CEILING, NOT TIDINESS. The route refuses
 * more than `MAX_ENTRIES_PER_SAVE` (60) entries in one request. With three boxes per role a
 * 24-role example would be 73 and the advisor would be told their click had failed. His own
 * workbook names no people, so skipping the empty `person` boxes brings it back to 49 — and
 * `tests/unit/orgChart.test.js` fails if a future example ever crosses that line, rather than
 * leaving it to be discovered by a refusal mid-session.
 *
 * @param {Array<{id: number, name: string, person: string, reportsTo: string}>} roles
 * @returns {Array<{fieldKey: string, value: string}>}
 */
function entriesForRoles (roles) {
  const list = Array.isArray(roles) ? roles : []
  const out = [{ fieldKey: ROSTER_KEY, value: list.map(r => r.id).join(',') }]
  list.forEach((r) => {
    const put = (part, value) => {
      if (value) { out.push({ fieldKey: roleKey(r.id, part), value }) }
    }
    put('name', r.name)
    put('person', r.person)
    put('head', r.reportsTo)
  })
  return out
}

/**
 * Rename a role, and carry the new name to everyone who reports to it.
 *
 * 🔴 THE ONE BEHAVIOUR THE DRAWING DOES NOT DESCRIBE, STATED RATHER THAN SLIPPED IN. A
 * Reporting Head holds a NAME, so renaming "COO" to "Operations Director" would otherwise
 * leave four roles reporting to a role that no longer exists — they would fall off the chart
 * and reappear under a dashed outside parent called COO, which is a wrong answer arrived at
 * silently. The alternative was storing an id, which cannot hold `Shareholders`.
 *
 * @param {Array<{id: number, name: string, reportsTo: string}>} roles
 * @param {number} id the role being renamed
 * @param {string} name its new name
 * @returns {Array<{id: number, name: string, reportsTo: string}>} a new list
 */
function renameCascade (roles, id, name) {
  const list = Array.isArray(roles) ? roles : []
  const target = list.find(r => r.id === id)
  const was = target ? String(target.name || '').trim() : ''
  const now = String(name === undefined || name === null ? '' : name)
  return list.map((r) => {
    // ⚠ `person` IS CARRIED THROUGH EVERY BRANCH. Rebuilding a role from three of its four
    // fields quietly deletes whoever is in it — renaming a position would have emptied it.
    if (r.id === id) { return { id: r.id, name: now, person: r.person, reportsTo: r.reportsTo } }
    // Only an exact match moves. A blank old name matches nothing, or every role with no
    // Reporting Head would be swept up the first time the first role was named.
    const head = String(r.reportsTo || '').trim()
    const follows = Boolean(was) && head === was
    return { id: r.id, name: r.name, person: r.person, reportsTo: follows ? now : r.reportsTo }
  })
}

/**
 * The roles that can be drawn — the ones the advisor has actually named.
 *
 * An unnamed row is a box waiting to be typed into, not a person; drawing it would put a
 * nameless rectangle on a client's chart.
 *
 * @param {Array<{id: number, name: string, reportsTo: string}>} roles
 * @returns {Array<{id: number, name: string, reportsTo: string}>}
 */
function namedRoles (roles) {
  return (Array.isArray(roles) ? roles : [])
    .map(r => ({
      id: r.id,
      name: String(r.name || '').trim(),
      // 🔴 THE PERSON NEVER DECIDES WHETHER A ROLE IS DRAWN — Decision B, ruled 2026-09-21.
      // A client redesigning their structure has positions before they have people, and his
      // own Board row could never hold one.
      person: String(r.person || '').trim(),
      reportsTo: String(r.reportsTo || '').trim()
    }))
    .filter(r => r.name)
}

/**
 * Resolve every role to its parent, and say where each one is anchored.
 *
 * Three ways a role has no parent inside the chart, and all three make it a top:
 * it names nobody; it names somebody who is not a role (an OUTSIDE parent, which his own
 * example does with `Shareholders`); or following its chain of heads comes back round to
 * itself, which is the loop the drawing promises to notice rather than block.
 *
 * @param {Array<{id: number, name: string, reportsTo: string}>} named
 * @returns {{parentOf: object, outsideOf: object, looped: object}}
 */
function resolve (named) {
  const byName = {}
  named.forEach((r) => { if (!byName[r.name]) { byName[r.name] = r } })

  const parentOf = {}
  const outsideOf = {}
  named.forEach((r) => {
    if (!r.reportsTo) { return }
    const parent = byName[r.reportsTo]
    // A role naming itself is its own outside parent in every sense that matters; treat it
    // as a loop of one rather than drawing a connector from a box to itself.
    if (parent && parent.id !== r.id) { parentOf[r.id] = parent.id } else if (parent) {
      parentOf[r.id] = r.id
    } else { outsideOf[r.id] = r.reportsTo }
  })

  // Walk each role's chain of heads. Anything that revisits a role already on this walk is
  // in a circle, and the role where the walk started is detached so that every role is still
  // drawn somewhere — "what the advisor typed is always kept".
  const looped = {}
  named.forEach((r) => {
    const seen = {}
    let at = r.id
    while (parentOf[at] !== undefined) {
      if (seen[at]) { looped[r.id] = true; break }
      seen[at] = true
      at = parentOf[at]
      if (at === r.id) { looped[r.id] = true; break }
    }
  })

  return { parentOf, outsideOf, looped }
}

/**
 * What the chart is, as boxes and connectors ready to draw.
 *
 * 🔴 THE LAYOUT IS THE DRAWING'S OWN. A leaf takes the next column across; a role with
 * children is centred over them. Laid against `strategy-capture-parent-child-list.html`
 * section 3 that reproduces all 24 of Mike's boxes and the outside parent above them,
 * coordinate for coordinate — which is what the test asserts, rather than that "a chart
 * appeared".
 *
 * @param {Array<{id: number, name: string, reportsTo: string}>} roles
 * @returns {{
 *   boxes: Array<{id: string, name: string, x: number, y: number, kind: string}>,
 *   links: Array<{id: string, d: string, kind: string}>,
 *   width: number, height: number, minY: number, viewBox: string,
 *   levels: number, roleCount: number
 * }}
 */
function layout (roles) {
  const named = namedRoles(roles)
  if (!named.length) {
    return { boxes: [], links: [], width: 0, height: 0, minY: 0, viewBox: '0 0 0 0', levels: 0, roleCount: 0 }
  }

  const { parentOf, outsideOf, looped } = resolve(named)

  const childrenOf = {}
  named.forEach((r) => {
    const p = looped[r.id] ? undefined : parentOf[r.id]
    if (p === undefined) { return }
    if (!childrenOf[p]) { childrenOf[p] = [] }
    childrenOf[p].push(r.id)
  })

  // The anchors, in the roster's own order: each distinct outside parent is one dashed box
  // with its children beneath it, and every other top stands alone.
  const anchors = []
  const outsideSeen = {}
  named.forEach((r) => {
    const isTop = looped[r.id] || parentOf[r.id] === undefined
    if (!isTop) { return }
    const outside = looped[r.id] ? '' : (outsideOf[r.id] || '')
    if (outside) {
      if (outsideSeen[outside]) {
        anchors[outsideSeen[outside].at].roots.push(r.id)
        return
      }
      outsideSeen[outside] = { at: anchors.length }
      anchors.push({ outside, roots: [r.id] })
      return
    }
    anchors.push({ outside: '', roots: [r.id] })
  })

  const byId = {}
  named.forEach((r) => { byId[r.id] = r })

  const x = {}
  const level = {}
  let slot = 0

  /**
   * Depth-first: leaves take columns left to right, parents settle over their children.
   * @param {number} id
   * @param {number} depth
   */
  function place (id, depth) {
    level[id] = depth
    const kids = childrenOf[id] || []
    if (!kids.length) {
      x[id] = slot * COL
      slot++
      return
    }
    kids.forEach(k => place(k, depth + 1))
    x[id] = Math.round((x[kids[0]] + x[kids[kids.length - 1]]) / 2)
  }

  const hasOutside = anchors.some(a => a.outside)
  anchors.forEach((a) => { a.roots.forEach(id => place(id, 0)) })
  // An outside parent settles over the roles that named it, exactly as any other parent does.
  anchors.forEach((a) => {
    if (!a.outside) { return }
    a.x = Math.round((x[a.roots[0]] + x[a.roots[a.roots.length - 1]]) / 2)
  })

  let deepest = 0
  named.forEach((r) => { if (level[r.id] > deepest) { deepest = level[r.id] } })

  const boxes = []
  const links = []

  /**
   * One connector: down half the gap, across, then down the rest. The same elbow for every
   * link, including an outside parent's — which is what lets an outside parent carry more
   * than one role beneath it.
   * @param {number} px @param {number} py @param {number} cx @param {number} cy
   * @returns {string}
   */
  function elbow (px, py, cx, cy) {
    return 'M' + (px + TEXT_MID) + ' ' + (py + BOX_H) +
      ' V' + (py + BOX_H + ELBOW) +
      ' H' + (cx + TEXT_MID) +
      ' V' + cy
  }

  anchors.forEach((a, i) => {
    if (!a.outside) { return }
    const oy = -ROW
    boxes.push({ id: 'o' + i, name: a.outside, person: '', x: a.x, y: oy, depth: -1, kind: 'outside' })
    a.roots.forEach((id) => {
      links.push({ id: 'lo' + i + '-' + id, d: elbow(a.x, oy, x[id], 0), kind: 'outside' })
    })
  })

  named.forEach((r) => {
    const top = looped[r.id] || parentOf[r.id] === undefined
    boxes.push({
      id: 'r' + r.id,
      name: r.name,
      person: r.person,
      x: x[r.id],
      y: level[r.id] * ROW,
      // 🔴 HOW FAR DOWN THE ORGANISATION THIS BOX SITS, and it is what colours it — Decision
      // E, ruled 2026-09-21. Depth is the one thing an org chart exists to show, and on the
      // screen this replaces every box was the same pale outline, so the top of the chart
      // looked exactly like the bottom.
      depth: level[r.id],
      kind: top ? 'root' : 'role'
    })
    const p = looped[r.id] ? undefined : parentOf[r.id]
    if (p === undefined) { return }
    links.push({
      id: 'l' + r.id,
      d: elbow(x[p], level[p] * ROW, x[r.id], level[r.id] * ROW),
      kind: 'role'
    })
  })

  const width = (slot - 1) * COL + BOX_W
  const minY = hasOutside ? -ROW : 0
  const height = deepest * ROW + BOX_H + (hasOutside ? ROW : 0) + PAD_BOTTOM

  return {
    boxes,
    links,
    width,
    height,
    minY,
    viewBox: '0 ' + minY + ' ' + width + ' ' + height,
    levels: deepest + 1,
    roleCount: named.length
  }
}

/**
 * What is worth saying about this chart — and it is only ever said, never enforced.
 *
 * 🔴 A NOTICE, NEVER A BLOCK. Mike's ruling of 2026-09-08 that a check *"never blocks the
 * advisor"*, applied here by the drawing itself: his own 24-role example raises one of these,
 * because `Board` reports to `Shareholders` and `Shareholders` is not one of the roles. It is
 * drawn above the chart as an outside parent and the session carries on.
 *
 * @param {Array<{id: number, name: string, reportsTo: string}>} roles
 * @returns {{outside: string[], looped: string[], tops: string[]}} names, in roster order
 */
function checks (roles) {
  const named = namedRoles(roles)
  const { parentOf, outsideOf, looped } = resolve(named)

  const outside = []
  const seen = {}
  const loopNames = []
  const tops = []

  named.forEach((r) => {
    if (looped[r.id]) {
      loopNames.push(r.name)
      tops.push(r.name)
      return
    }
    const name = outsideOf[r.id]
    if (name) {
      if (!seen[name]) { seen[name] = true; outside.push(name); tops.push(name) }
      return
    }
    if (parentOf[r.id] === undefined) { tops.push(r.name) }
  })

  return { outside, looped: loopNames, tops }
}

/**
 * The seven bands, top of the house to front line — Decision E, ruled 2026-09-21.
 *
 * 🔴 EVERY COLOUR IS ALREADY IN `design/BRAND-TOKENS.md`. Navy `#002B64`, Blue `#0070C0`,
 * Cyan `#00B1E0` and Sky `#7FD3F1` are his; the three between them are steps along the ramp
 * those four describe. Nothing is invented here, and a new colour must not be added without
 * that file saying so first.
 *
 * ⚠ THE COST IS ACCEPTED AND STATED: printed in black and white every band collapses to grey.
 * The connectors still carry the structure so nothing becomes wrong, but the readability this
 * buys on screen is the first thing a photocopier takes away.
 */
const BANDS = [
  { fill: '#002B64', role: '#FFFFFF', person: '#9DC2E8' },
  { fill: '#0A4A8F', role: '#FFFFFF', person: '#AFD2EE' },
  { fill: '#0070C0', role: '#FFFFFF', person: '#CFE6F7' },
  { fill: '#2E90D9', role: '#FFFFFF', person: '#DCEEFA' },
  { fill: '#00B1E0', role: '#00294F', person: '#0B4A72' },
  { fill: '#7FD3F1', role: '#00294F', person: '#12587F' },
  { fill: '#C7E9F8', role: '#00294F', person: '#1C6489' }
]

/**
 * The band a box at this depth is painted in. Anything below the last one keeps the last —
 * a chart deeper than seven levels stays readable rather than running out of colours.
 *
 * @param {number} depth
 * @returns {{fill: string, role: string, person: string}}
 */
function bandFor (depth) {
  const d = Number.isInteger(depth) && depth > 0 ? depth : 0
  return BANDS[Math.min(d, BANDS.length - 1)]
}

module.exports = {
  ROSTER_KEY,
  MAX_ROLES,
  BOX_W,
  BOX_H,
  TEXT_ROLE,
  TEXT_ROLE_ALONE,
  TEXT_PERSON,
  TEXT_MID,
  BANDS,
  bandFor,
  isOrgChartKey,
  roleKey,
  rolesFrom,
  nextRoleId,
  entriesForRoles,
  renameCascade,
  namedRoles,
  layout,
  checks
}
