/**
 * @file The one rule that decides whether a concept can be put on a step.
 * @module utils/strategyCards
 *
 * Item 15.1.
 *
 * 🔴 ONE RULE, ONE HOME, TWO SCREENS. The advisor's Build session
 * (`pages/strategy-planner.vue`) and the manager's authoring screen
 * (`components/firm/FirmSessionProcess.vue`) must admit exactly the same concepts. A
 * concept offered on the authoring screen and not on the advisor's arrives as a step with
 * nothing in it and no explanation — and both screens render that perfectly happily.
 * Written twice, the two copies would drift the first time either half of the rule changed.
 *
 * ⚠ IT LIVES HERE AND NOT BESIDE `hasConceptGraphic`, DELIBERATELY.
 * `components/strategy/concepts/index.js` is GENERATED by
 * `scripts/build-concept-graphics.js`; a helper added there is overwritten by the next
 * build, and `tests/unit/conceptGraphics.test.js` fails the build to say so. It was put
 * there once, on 2026-09-21, and that guard caught it the same hour.
 */

import { hasConceptGraphic } from '~/components/strategy/concepts'

/**
 * May this concept be put on a step at all?
 *
 * 🔴 A TABLE **OR** A DRAWING — Mike's ruling, 2026-09-20. It used to demand a supplied
 * workbook, which capped the 33 approved drawings at the 16 concepts that had one: a
 * concept with a drawing and no table now teaches from Mike's own page, so excluding it
 * loses real content rather than sparing the client a blank.
 *
 * @param {boolean} hasTable - whether the concept's capture table was supplied
 * @param {string} conceptId
 * @returns {boolean}
 */
export function isPlaceableConcept (hasTable, conceptId) {
  return Boolean(hasTable) || hasConceptGraphic(conceptId)
}
