'use strict'

/**
 * CONTENT ROUTING — which content assists a CLIENT RECOMMENDATION, and which is
 * only ever read by an advisor.
 *
 * Why this file exists. Content filed into the wrong lane is invisible: it
 * renders on screen, it saves, it passes tests, and it silently never reaches
 * the decision it was authored for. That has now happened three times in this
 * codebase — the domain-support storage-key defect, the Course Builder
 * session-briefing defect, and the near-miss on 2026-07-31 where three
 * client-facing logic tables were about to be filed as `flat_if_then`, a shape
 * the engine documents as "never walked, and never fed into the client
 * recommendation path" (logicTrees.js). All three were found by hand.
 *
 * This module is the single place that decides an asset's lane. The build guard
 * (tests/unit/contentRouting.test.js) and any human-readable report both read
 * it, so the guard and the report can never disagree — a report generated by
 * its own private copy of these rules is a report that drifts.
 *
 * It classifies; it does not judge. A lane is not a quality mark: ai-briefing
 * content is doing exactly its job by NOT selecting templates.
 */

const path = require('path')
const fs = require('fs')

const logicTreeData = require('../../data/logic_trees.json')
const templates = require('../../data/templates.json')
const courseQuizzes = require('../../data/course-quizzes.json')
const advisoryDistinctions = require('../../data/advisory-distinctions.json')

const DATA_DIR = path.join(__dirname, '..', '..', 'data')

/**
 * The lanes. UNKNOWN is deliberately a real value rather than an omission —
 * an asset this module cannot place must be visible and must fail the build,
 * never be quietly dropped from the count or defaulted into a lane.
 */
const LANES = {
  CLIENT_RECOMMENDATION: 'client-recommendation',
  AI_BRIEFING: 'ai-briefing',
  ADVISOR_READ_ONLY: 'advisor-read-only',
  UNKNOWN: 'unknown'
}

/**
 * Plain-English meaning of each lane, for the report and for anyone reading a
 * failure message. Kept here so there is one wording, not one per surface.
 */
const LANE_DESCRIPTIONS = {
  [LANES.CLIENT_RECOMMENDATION]:
    'Influences which templates a client is recommended. A change here changes what advisors see on their cards.',
  [LANES.AI_BRIEFING]:
    'Briefs the AI on the client path but does NOT select templates. Changes the wording and depth of what the AI says, not which pages it picks.',
  [LANES.ADVISOR_READ_ONLY]:
    'Only ever read by an advisor or learner. Never reaches a client recommendation.',
  [LANES.UNKNOWN]:
    'Could not be classified from the data. Treat as a defect — either the asset is malformed or this module has not caught up with a new shape.'
}

/**
 * Classifies every logic tree by its SHAPE, which is what the engine acts on.
 *
 * A `nodes` tree is walked by walkLogicTree and its `nodes[].templates` become
 * client recommendations. A `flat_if_then` tree is formatted as plain reference
 * text for Learn mode and is never walked (logicTrees.js — "Get-the-Job content
 * must not reach client templates", design §2.5). The distinction is invisible
 * on screen: both render as an IF/THEN grid in Firm Manager.
 *
 * @returns {Array<Object>} one row per tree
 */
function classifyLogicTrees () {
  return (logicTreeData.trees || []).map((tree) => {
    const hasNodes = Array.isArray(tree.nodes) && tree.nodes.length > 0
    const isFlat = tree.type === 'flat_if_then'

    let lane = LANES.UNKNOWN
    let decidedBy = 'neither a `nodes` graph nor a `flat_if_then` branch list'

    if (hasNodes && !isFlat) {
      lane = LANES.CLIENT_RECOMMENDATION
      decidedBy = '`nodes` graph — walked by walkLogicTree; its nodes[].templates become client recommendations'
    } else if (isFlat && !hasNodes) {
      lane = LANES.ADVISOR_READ_ONLY
      decidedBy = '`flat_if_then` — formatted as Learn-mode reference only; never walked (logicTrees.js, design §2.5)'
    } else if (hasNodes && isFlat) {
      // Both shapes at once: the engine would walk the nodes and ALSO print the
      // branches as reference. Ambiguous by construction, so it is not guessed.
      decidedBy = 'declares BOTH `nodes` and `flat_if_then` — the engine would treat it as two different things'
    }

    return {
      family: 'logic-tree',
      id: tree.id,
      name: tree.name || tree.id,
      lane,
      decidedBy,
      evidence: `data/logic_trees.json · nodes=${hasNodes ? (tree.nodes || []).length : 0} · type=${tree.type || '(none)'}`
    }
  })
}

/**
 * Classifies each domain-support file.
 *
 * All of them sit in the same lane, and that is the point worth recording: the
 * §0.6 ruling is that a domain-support document BRIEFS the AI, it does not pick
 * templates — selection is resolveTemplatesWithOutlier + walkLogicTree +
 * distinctions, none of which read domain support. Anyone assuming a firm's
 * edits here change which pages get recommended is wrong, and this row is where
 * they find that out.
 *
 * `dev-firm-domain-support.json` is excluded: it is the dev-mode firm OVERRIDE
 * store, not a platform domain.
 *
 * @returns {Array<Object>} one row per domain-support file
 */
function classifyDomainSupport () {
  const files = fs.readdirSync(DATA_DIR)
    .filter(f => f.endsWith('-domain-support.json') && !f.startsWith('dev-'))
    .sort()

  return files.map((file) => {
    const parsed = JSON.parse(fs.readFileSync(path.join(DATA_DIR, file), 'utf8'))
    const materialCount = Array.isArray(parsed.materials) ? parsed.materials.length : 0
    const legacyCount = parsed.support_tools ? Object.keys(parsed.support_tools).length : 0

    return {
      family: 'domain-support',
      id: parsed.domain || file.replace('-domain-support.json', ''),
      name: parsed.label || parsed.domain || file,
      lane: LANES.AI_BRIEFING,
      decidedBy: 'read only by the domainSupport formatters, which feed the prompt — template selection never reads it (§0.6)',
      evidence: `data/${file} · materials=${materialCount}${legacyCount ? ` · legacy support_tools=${legacyCount}` : ''}`
    }
  })
}

/**
 * Classifies each library template by `includedInClient`, the flag the master
 * export carries to say whether a page may be put in front of a client.
 *
 * @returns {Array<Object>} one row per template
 */
function classifyTemplates () {
  return templates.map((t) => {
    const flag = t.includedInClient
    let lane = LANES.UNKNOWN
    let decidedBy = '`includedInClient` is absent or not a boolean'

    if (flag === true) {
      lane = LANES.CLIENT_RECOMMENDATION
      decidedBy = '`includedInClient: true` — eligible to be recommended to a client'
    } else if (flag === false) {
      lane = LANES.ADVISOR_READ_ONLY
      decidedBy = '`includedInClient: false` — advisor-facing library page, not put in front of a client'
    }

    return {
      family: 'template',
      id: t.page || t.title,
      name: t.title,
      lane,
      decidedBy,
      evidence: `data/templates.json · section=${t.section || '(none)'}`
    }
  })
}

/**
 * Classifies each CB-30 quiz bank.
 *
 * Quiz banks are required only by courseEngine.js (question generation and
 * grading). No require chain reaches them from advisorEngine.js or
 * templateResolver.js, so a bank cannot move a recommendation.
 *
 * @returns {Array<Object>} one row per bank
 */
function classifyQuizBanks () {
  const banks = (courseQuizzes && courseQuizzes.banks) || {}

  return Object.keys(banks)
    // `_comment` is a documentation string sitting alongside the banks, not an
    // asset. Counting it reported 63 banks where the firm has 62 — a wrong number
    // in a governance report is the failure this report exists to prevent.
    // Fixed 2026-08-01; the guard now rejects any `_`-prefixed id.
    .filter(key => !key.startsWith('_'))
    .sort()
    .map((key) => {
      const bank = banks[key] || {}
      // `entries`, NOT `questions`. courseEngine.js L455/L550 and
      // firmQuizzes.js L99 all read `bank.entries`; nothing anywhere reads
      // `bank.questions`. Reading the wrong field printed "questions=0" on
      // every one of the 62 banks while the lane stayed correct, so the row
      // looked classified and its evidence was false. Fixed 2026-08-01.
      const questions = Array.isArray(bank.entries) ? bank.entries.length : 0

      return {
        family: 'quiz-bank',
        id: key,
        name: key,
        lane: LANES.ADVISOR_READ_ONLY,
        decidedBy: 'required only by courseEngine.js — no path from the advisor engine or the template resolver',
        evidence: `data/course-quizzes.json · questions=${questions}`
      }
    })
}

/**
 * Classifies each platform advisory distinction.
 *
 * A distinction carries a `boost` that is added directly to a template's score
 * in templateResolver.js, so it moves recommendations by design. A distinction
 * with no templates and no boost cannot move anything, and is reported as such
 * rather than being counted as live.
 *
 * @returns {Array<Object>} one row per distinction
 */
function classifyDistinctions () {
  const rows = (advisoryDistinctions && advisoryDistinctions.platform) || []

  return rows.map((d) => {
    const boost = Number(d.boost) || 0
    const targets = Array.isArray(d.templates) ? d.templates.length : 0
    const canMove = boost > 0 && targets > 0

    return {
      family: 'distinction',
      id: d.id,
      name: d.description || d.id,
      lane: canMove ? LANES.CLIENT_RECOMMENDATION : LANES.ADVISOR_READ_ONLY,
      decidedBy: canMove
        ? `boost +${boost} added to ${targets} template(s) in templateResolver.js`
        : 'no boost or no target templates — cannot change a score',
      evidence: `data/advisory-distinctions.json · domain=${d.domain || '(none)'} · boost=${boost} · templates=${targets}`
    }
  })
}

/**
 * Every content asset in the app, with the lane it sits in and why.
 *
 * @returns {Array<{family:string,id:string,name:string,lane:string,decidedBy:string,evidence:string}>}
 */
function classifyAllContent () {
  return [].concat(
    classifyLogicTrees(),
    classifyDomainSupport(),
    classifyTemplates(),
    classifyQuizBanks(),
    classifyDistinctions()
  )
}

/**
 * Counts by family and lane, for a report header or a failure message.
 *
 * @param {Array<Object>} [rows] - defaults to a fresh classification
 * @returns {{total:number, byLane:Object, byFamily:Object, unknown:Array<Object>}}
 */
function summariseRouting (rows) {
  const all = rows || classifyAllContent()
  const byLane = {}
  const byFamily = {}

  for (const row of all) {
    byLane[row.lane] = (byLane[row.lane] || 0) + 1
    byFamily[row.family] = byFamily[row.family] || {}
    byFamily[row.family][row.lane] = (byFamily[row.family][row.lane] || 0) + 1
  }

  return {
    total: all.length,
    byLane,
    byFamily,
    unknown: all.filter(r => r.lane === LANES.UNKNOWN)
  }
}

module.exports = {
  LANES,
  LANE_DESCRIPTIONS,
  classifyLogicTrees,
  classifyDomainSupport,
  classifyTemplates,
  classifyQuizBanks,
  classifyDistinctions,
  classifyAllContent,
  summariseRouting
}
