'use strict'

/**
 * cpdCatalogue — what CPD an advisor may claim, and what each claim is worth.
 *
 * The master export carries three authored time allowances on every template, in
 * `cpd`: `watchedVideo` (the tutorial video), `reviewTemplate` (reading it) and
 * `reheasedTemplate` (rehearsing it with a colleague). Until now only the first was
 * ever read, and only to add a sentence to advice — the other two, some 82 hours
 * across the library, were never used at all.
 *
 * WHAT THIS MODULE IS FOR. A CPD claim is a professional declaration an advisor may
 * submit to their own body, so **nothing about its value may come from the browser**.
 * The client names a template and an activity; the minutes, the template's identity
 * and the wording of the pledge are all resolved HERE, server-side, from the export.
 *
 * WHY MINUTES ARE FROZEN INTO THE CLAIM ROW rather than looked up at read time: the
 * master export is re-authored and swapped wholesale (`data/templates.json` has been
 * replaced five times since May). A total an advisor has already pledged to, and may
 * already have submitted, must never change underneath them. Same principle as the
 * capability tier, which is likewise computed at write time.
 *
 * THREE FACTS ABOUT THE EXPORT THIS HAS TO SURVIVE — all verified against the real
 * file 2026-07-29, none of them editable here (the export is generated by the master
 * app and is never hand-corrected in this repo):
 *
 * 1. `cpd.isHidden` marks a record as not CPD-bearing. 183 of 289 records are hidden.
 *    All but one carry zeroes anyway; the exception ("Business Purchase Assessment 1",
 *    15 minutes' reading, with no visible twin) is deliberately NOT claimable — the
 *    master app has marked it hidden, and honouring that is the conservative reading.
 *    Hidden records are skipped before the collision rule, so a hidden duplicate can
 *    never beat the real record.
 * 2. **Neither `page` nor `title` is unique.** 21 page ids and 5 titles appear on more
 *    than one record, and 10 of those disagree about CPD time. Identity here is
 *    therefore the normalised TITLE (which is what the activity tables actually store),
 *    and collisions are resolved by the rule below.
 * 3. Two allowances are fractional (15.2 and 24.23 minutes). They are rounded to whole
 *    minutes; anything that rounds below 1 is not claimable.
 *
 * COLLISION RULE — never over-claim. Between two visible records for one title, a
 * record carrying time beats an all-zero one, and where both carry time the LOWER
 * total wins and the disagreement is logged. Picking the higher figure would inflate a
 * regulated claim on the strength of a data defect; picking the lower is conservative,
 * and the log means it is reconciled rather than silently absorbed. Against the current
 * export exactly one title is affected ("Advisor Prep", 84 vs 120 minutes).
 *
 * CPD FOLLOWS THE LIBRARY IN FORCE (Mike's ruling, 2026-09-01, item 4.56). Since
 * Cascade Phase 2 the AI recommends from whichever library a firm's tier chain has
 * uploaded (templateLibrary.loadEffectiveTemplates), so what an advisor may claim must
 * be priced from that SAME library — recommendations and claimable minutes must always
 * agree. `catalogueFor(scopeId)` is the scoped entry point routes use; the module-level
 * lookups below it remain the PLATFORM view (the committed seed) for callers with no
 * firm in hand, which is also the exact behaviour every scope gets until a tier
 * uploads. Safe because every export is generated by Advisor-e, never hand-edited by a
 * firm — and every rule above (hidden records, the lower-figure collision rule, minutes
 * frozen into the claim row at claim time) applies to a firm's library identically,
 * because the same index build runs over it.
 */

const { getOrgTemplates } = require('./templates')

/**
 * Lazy-required, same pattern as advisorEngine: templateLibrary pulls in the whole
 * store stack (firmOverlay → db), which the many callers that only want the platform
 * view — and their tests — should not have to load.
 */
let _loadEffectiveTemplates = null
function loadEffectiveTemplates (...args) {
  if (!_loadEffectiveTemplates) { _loadEffectiveTemplates = require('./templateLibrary').loadEffectiveTemplates }
  return _loadEffectiveTemplates(...args)
}

/** The three claimable activities, in the order an advisor works through them. */
const ACTIVITIES = ['video', 'reading', 'rehearsal']

/**
 * Master-export field per activity. `reheasedTemplate` is misspelled IN THE EXPORT —
 * read as-is, because the export is never hand-edited here.
 */
const ACTIVITY_FIELD = {
  video: 'watchedVideo',
  reading: 'reviewTemplate',
  rehearsal: 'reheasedTemplate'
}

/**
 * The declaration the advisor agrees to, per activity. Stored as a KEY plus a version
 * on every claim, never as free text: if the wording is ever changed, an older claim
 * must still show the words that advisor actually agreed to. Bump PLEDGE_VERSION when
 * any of these strings changes meaning.
 */
const ACTIVITY_PLEDGE = {
  video: 'cpd.pledge.video',
  reading: 'cpd.pledge.reading',
  rehearsal: 'cpd.pledge.rehearsal'
}
const PLEDGE_VERSION = 1

/** An allowance below a minute is not a claimable activity. */
const MIN_MINUTES = 1
/** A day. Nothing real approaches it; it bounds a corrupt export, not a design choice. */
const MAX_MINUTES = 1440
/** Column widths in advisor_cpd_claims — a value longer than this is not a real title. */
const MAX_TITLE_LENGTH = 255
const MAX_PAGE_LENGTH = 64

let _byTitle = null
/** @type {WeakMap<Array, Map<string, object>>} one built index per firm library array. */
let _byLibrary = new WeakMap()

/**
 * The lookup key for a template name: case- and whitespace-insensitive.
 *
 * Both sources of stored names run through this. It matters because they are stored
 * differently — `recommended_templates` holds lowercased names (tierLookup emits the
 * lowercase key), while `session_resources` holds the library's exact spelling.
 *
 * @param {*} name @returns {string} the normalised key, '' when there is no usable name.
 */
function normaliseTitle (name) {
  if (typeof name !== 'string') { return '' }
  return name.toLowerCase().trim().replace(/\s+/g, ' ')
}

/**
 * The whole minutes claimable for one activity on one record.
 *
 * @param {object} cpd - the record's `cpd` block.
 * @param {string} activity - one of ACTIVITIES.
 * @returns {number} whole minutes, or 0 when this activity is not claimable.
 */
function activityMinutes (cpd, activity) {
  const raw = cpd ? cpd[ACTIVITY_FIELD[activity]] : null
  if (typeof raw !== 'number' || !Number.isFinite(raw)) { return 0 }
  const whole = Math.round(raw)
  if (whole < MIN_MINUTES || whole > MAX_MINUTES) { return 0 }
  return whole
}

/**
 * One catalogue entry per distinct visible template title.
 *
 * @param {object} record - a template record from the library.
 * @returns {{title: string, page: string|null, activities: object[], totalMinutes: number}}
 */
function buildEntry (record) {
  const activities = []
  let totalMinutes = 0
  for (const activity of ACTIVITIES) {
    const minutes = activityMinutes(record.cpd, activity)
    if (!minutes) { continue }
    activities.push({
      activity,
      minutes,
      pledgeKey: ACTIVITY_PLEDGE[activity],
      pledgeVersion: PLEDGE_VERSION
    })
    totalMinutes += minutes
  }
  const page = typeof record.page === 'string' && record.page.trim()
    ? record.page.trim().slice(0, MAX_PAGE_LENGTH)
    : null
  return {
    title: String(record.title).trim().slice(0, MAX_TITLE_LENGTH),
    page,
    activities,
    totalMinutes
  }
}

/**
 * Build the title → entry index, applying the hidden-record and collision rules.
 *
 * @param {Array<object>} records - the template library to price CPD from.
 * @returns {Map<string, object>}
 */
function buildIndex (records) {
  const byTitle = new Map()
  const ambiguous = []

  for (const record of records) {
    // A hidden record is not CPD-bearing. Checked before anything else so a hidden
    // duplicate can never win a collision against the real record.
    if (!record || !record.cpd || record.cpd.isHidden === true) { continue }
    const key = normaliseTitle(record.title)
    if (!key) { continue }

    const entry = buildEntry(record)
    const held = byTitle.get(key)
    if (!held) { byTitle.set(key, entry); continue }

    // Both carry time and disagree: keep the lower, and say so — never absorb a data
    // defect silently into a figure an advisor will declare to their professional body.
    if (held.totalMinutes > 0 && entry.totalMinutes > 0 &&
        held.totalMinutes !== entry.totalMinutes) {
      ambiguous.push(`"${entry.title}" (${held.totalMinutes} vs ${entry.totalMinutes} minutes)`)
    }
    // A record carrying time beats one carrying none. (Two records that BOTH carry
    // none are interchangeable — neither is claimable — which is why a mutant
    // swapping them survives the suite: there is no observable difference to catch.)
    if (held.totalMinutes === 0 && entry.totalMinutes > 0) {
      byTitle.set(key, entry)
    } else if (entry.totalMinutes > 0 && held.totalMinutes > 0 &&
               entry.totalMinutes < held.totalMinutes) {
      byTitle.set(key, entry)
    }
  }

  if (ambiguous.length) {
    console.warn('[cpdCatalogue] the master export gives more than one CPD time for ' +
      `${ambiguous.length} template(s) — the LOWER figure is used, never the higher: ` +
      ambiguous.join('; '))
  }
  return byTitle
}

/** Built on first use, not at require time, so tests control when the file is read. */
function index () {
  if (!_byTitle) { _byTitle = buildIndex(getOrgTemplates(null)) }
  return _byTitle
}

/**
 * The index for a given library — a firm's uploaded set, or the platform seed.
 *
 * Keyed by the ARRAY ITSELF: templateLibrary hands back the same cached array for a
 * scope until its ~60s TTL lapses, so an index is rebuilt at most once a minute per
 * scope and expires with the library it was built from. Anything that is not a
 * non-empty array means "no library in force" and reads the seed — the same
 * fall-through loadEffectiveTemplates itself documents.
 *
 * @param {Array<object>|null} records - the library in force, or null for the seed.
 * @returns {Map<string, object>}
 */
function indexFor (records) {
  if (!Array.isArray(records) || records.length === 0) { return index() }
  let idx = _byLibrary.get(records)
  if (!idx) {
    idx = buildIndex(records)
    _byLibrary.set(records, idx)
  }
  return idx
}

/** Drop the cached indexes. For tests, and for a reload after an export swap. */
function resetCache () {
  _byTitle = null
  _byLibrary = new WeakMap()
}

/**
 * The catalogue entry for one template name in a given index, or null when it is
 * unknown or carries no claimable CPD time.
 *
 * @param {Map<string, object>} idx - the index for the library in force.
 * @param {*} name - a template name as stored on an activity row.
 * @returns {object|null} a COPY — callers must not be able to mutate the index.
 */
function lookupIn (idx, name) {
  const entry = idx.get(normaliseTitle(name))
  if (!entry || !entry.activities.length) { return null }
  return {
    title: entry.title,
    page: entry.page,
    totalMinutes: entry.totalMinutes,
    activities: entry.activities.map(a => ({ ...a }))
  }
}

/**
 * The catalogue entry for one template name in the PLATFORM view (the committed
 * seed). Scoped callers go through `catalogueFor` / `catalogueForLibrary` instead.
 *
 * @param {*} name - a template name as stored on an activity row.
 * @returns {object|null} a COPY — callers must not be able to mutate the index.
 */
function lookupTemplate (name) {
  return lookupIn(index(), name)
}

/**
 * Everything an advisor may claim, given the template names their own sessions used.
 *
 * Duplicates across sessions collapse to one entry — a template used in three sessions
 * is one template with three claimable activities, not three. How MANY times each may
 * be claimed is deliberately not limited here: an advisor who watched a video three
 * times because the concept was hard has done the work three times, and the record
 * should say so (owner ruling, 2026-07-29).
 *
 * @param {Array<*>} names - template names from the advisor's own stored rows.
 * @returns {object[]} entries in the order first seen (callers sort for display).
 */
function claimableFor (names) {
  return claimableIn(index(), names)
}

/** `claimableFor` over an explicit index — the scoped catalogues bind to this. */
function claimableIn (idx, names) {
  if (!Array.isArray(names)) { return [] }
  const out = []
  const seen = new Set()
  for (const name of names) {
    const key = normaliseTitle(name)
    if (!key || seen.has(key)) { continue }
    seen.add(key)
    const entry = lookupIn(idx, key)
    if (entry) { out.push(entry) }
  }
  return out
}

/**
 * Resolve one claim to the exact values that will be stored.
 *
 * Everything of consequence is decided here rather than accepted from the request:
 * the minutes, the template's real title and page, and which pledge the advisor is
 * making. The client only ever names a template and an activity.
 *
 * @param {*} name - the template the advisor named.
 * @param {*} activity - one of ACTIVITIES.
 * @returns {{title: string, page: string|null, activity: string, minutes: number,
 *   pledgeKey: string, pledgeVersion: number}|null} null when this is not claimable.
 */
function resolveClaim (name, activity) {
  return resolveClaimIn(index(), name, activity)
}

/** `resolveClaim` over an explicit index — the scoped catalogues bind to this. */
function resolveClaimIn (idx, name, activity) {
  // Defence in depth, and deliberately kept though a mutation test shows removing it
  // changes nothing today: the `find` below is what actually rejects an unknown
  // activity. This states the allowlist at the top of the function so a later change
  // to the lookup cannot quietly widen what may be claimed.
  if (typeof activity !== 'string' || !ACTIVITIES.includes(activity)) { return null }
  const entry = lookupIn(idx, name)
  if (!entry) { return null }
  const found = entry.activities.find(a => a.activity === activity)
  if (!found) { return null }
  return {
    title: entry.title,
    page: entry.page,
    activity,
    minutes: found.minutes,
    pledgeKey: found.pledgeKey,
    pledgeVersion: found.pledgeVersion
  }
}

/**
 * Normalise the two client-supplied values on a claim request.
 *
 * Treated as hostile: only a string of sane length may be a template name, and the
 * activity must be one of the three known values — never coerced into one.
 *
 * @param {*} raw - the request body.
 * @returns {{templateTitle: string, activity: string}|null}
 */
function normaliseClaimRequest (raw) {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) { return null }
  const title = typeof raw.templateTitle === 'string' ? raw.templateTitle.trim() : ''
  if (!title || title.length > MAX_TITLE_LENGTH) { return null }
  const activity = typeof raw.activity === 'string' ? raw.activity.trim() : ''
  if (!ACTIVITIES.includes(activity)) { return null }
  return { templateTitle: title, activity }
}

/**
 * A catalogue bound to one library array — the seam courseEffort uses, because its
 * callers already hold the library the course was built from.
 *
 * @param {Array<object>|null} records - the library in force; anything that is not a
 *   non-empty array binds to the platform seed.
 * @returns {{lookupTemplate: Function, claimableFor: Function, resolveClaim: Function}}
 */
function catalogueForLibrary (records) {
  const idx = indexFor(records)
  return {
    lookupTemplate: name => lookupIn(idx, name),
    claimableFor: names => claimableIn(idx, names),
    resolveClaim: (name, activity) => resolveClaimIn(idx, name, activity)
  }
}

/**
 * The catalogue for a scope — CPD priced from whichever library is in force for it
 * (firm → group → global → platform, the templateLibrary walk). The entry point the
 * CPD routes use.
 *
 * Never rejects: loadEffectiveTemplates absorbs every store fault by its own contract
 * and returns null, which binds to the seed — a CPD read must not be what kills the
 * request.
 *
 * @param {string|null} scopeId - the authenticated firm/tier scope (req.firmId),
 *   never client-supplied.
 * @returns {Promise<{lookupTemplate: Function, claimableFor: Function,
 *   resolveClaim: Function}>}
 */
async function catalogueFor (scopeId) {
  return catalogueForLibrary(await loadEffectiveTemplates(scopeId))
}

module.exports = {
  claimableFor,
  lookupTemplate,
  resolveClaim,
  catalogueFor,
  catalogueForLibrary,
  normaliseClaimRequest,
  normaliseTitle,
  resetCache,
  ACTIVITIES,
  ACTIVITY_FIELD,
  ACTIVITY_PLEDGE,
  PLEDGE_VERSION,
  MAX_TITLE_LENGTH,
  MAX_MINUTES
}
