'use strict'

// cpdCatalogue decides what an advisor is ALLOWED to claim and what each claim is
// worth. Those figures become a professional declaration, so this file is held to the
// 100% standard CLAUDE.md sets for functions processing untrusted or consequential
// data: a wrong minute count here is submitted to a professional body, and a claim
// offered against a template the export hides is one nobody authorised.
//
// The template library is mocked throughout. The real export is replaced wholesale on
// every master release (five times since May 2026), so pinning behaviour to today's
// file would produce a suite that breaks on someone else's content change.

jest.mock('../../server/utils/templates', () => ({
  getOrgTemplates: jest.fn(() => [])
}))
// The cascade seam (item 4.56): what library is in force for a scope. Mocked so no
// test here touches the store stack; null means "no tier has uploaded" — the seed.
jest.mock('../../server/utils/templateLibrary', () => ({
  loadEffectiveTemplates: jest.fn(() => Promise.resolve(null))
}))

const { getOrgTemplates } = require('../../server/utils/templates')
const { loadEffectiveTemplates } = require('../../server/utils/templateLibrary')
const cpd = require('../../server/utils/cpdCatalogue')

/** A template record in the shape the master export actually produces. */
const record = over => Object.assign({
  page: 'id-1',
  title: 'E.O.Y Meeting',
  cpd: { isHidden: false, watchedVideo: 9, reviewTemplate: 60, reheasedTemplate: 30 }
}, over)

/** Point the catalogue at a library and drop the cached index. */
function library (records) {
  getOrgTemplates.mockReturnValue(records)
  cpd.resetCache()
}

let warn
beforeEach(() => {
  jest.clearAllMocks()
  loadEffectiveTemplates.mockResolvedValue(null)
  warn = jest.spyOn(console, 'warn').mockImplementation(() => {})
})
afterEach(() => warn.mockRestore())

// ── Reading the three allowances ──────────────────────────────────────────────

describe('the three activities', () => {
  test('reads video, reading and rehearsal from their export fields', () => {
    library([record()])

    const entry = cpd.lookupTemplate('E.O.Y Meeting')

    expect(entry.activities).toEqual([
      { activity: 'video', minutes: 9, pledgeKey: 'cpd.pledge.video', pledgeVersion: 1 },
      { activity: 'reading', minutes: 60, pledgeKey: 'cpd.pledge.reading', pledgeVersion: 1 },
      { activity: 'rehearsal', minutes: 30, pledgeKey: 'cpd.pledge.rehearsal', pledgeVersion: 1 }
    ])
    expect(entry.totalMinutes).toBe(99)
  })

  test('rehearsal reads the export\'s MISSPELLED field, not a corrected one', () => {
    // The export spells it `reheasedTemplate`. It is generated by the master app and
    // never hand-edited here, so a "tidied" field name would silently read nothing.
    library([record({ cpd: { isHidden: false, watchedVideo: 0, reviewTemplate: 0, rehearsedTemplate: 45 } })])

    expect(cpd.lookupTemplate('E.O.Y Meeting')).toBeNull()
  })

  test('an activity with no allowance is not offered', () => {
    library([record({ cpd: { isHidden: false, watchedVideo: 0, reviewTemplate: 60, reheasedTemplate: 0 } })])

    const entry = cpd.lookupTemplate('E.O.Y Meeting')

    expect(entry.activities.map(a => a.activity)).toEqual(['reading'])
    expect(entry.totalMinutes).toBe(60)
  })

  test('a template with no claimable time at all is not in the catalogue', () => {
    library([record({ cpd: { isHidden: false, watchedVideo: 0, reviewTemplate: 0, reheasedTemplate: 0 } })])

    expect(cpd.lookupTemplate('E.O.Y Meeting')).toBeNull()
  })
})

// ── The minutes themselves ────────────────────────────────────────────────────

describe('minutes', () => {
  test('a fractional allowance is rounded to whole minutes', () => {
    // Two real records carry 15.2 and 24.23. A claim is recorded in whole minutes.
    library([record({ cpd: { isHidden: false, watchedVideo: 15.2, reviewTemplate: 24.23, reheasedTemplate: 0 } })])

    const entry = cpd.lookupTemplate('E.O.Y Meeting')

    expect(entry.activities.map(a => a.minutes)).toEqual([15, 24])
  })

  test('an allowance that rounds below a minute is not claimable', () => {
    library([record({ cpd: { isHidden: false, watchedVideo: 0.4, reviewTemplate: 0, reheasedTemplate: 0 } })])

    expect(cpd.lookupTemplate('E.O.Y Meeting')).toBeNull()
  })

  test('an absurd allowance is refused rather than clamped into something plausible', () => {
    // Clamping would invent a figure. A corrupt export should offer nothing.
    library([record({ cpd: { isHidden: false, watchedVideo: 99999, reviewTemplate: 0, reheasedTemplate: 0 } })])

    expect(cpd.lookupTemplate('E.O.Y Meeting')).toBeNull()
  })

  test.each([
    ['a negative allowance', -30],
    ['a numeric string', '60'],
    ['null', null],
    ['undefined', undefined],
    ['NaN', NaN],
    ['Infinity', Infinity],
    ['an object', {}]
  ])('%s is not claimable time', (_label, value) => {
    library([record({ cpd: { isHidden: false, watchedVideo: value, reviewTemplate: 0, reheasedTemplate: 0 } })])

    expect(cpd.lookupTemplate('E.O.Y Meeting')).toBeNull()
  })

  test('a record with no cpd block at all is skipped', () => {
    library([record({ cpd: undefined })])

    expect(cpd.lookupTemplate('E.O.Y Meeting')).toBeNull()
  })

  test('a null entry in the library does not throw', () => {
    library([null, record()])

    expect(cpd.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(99)
  })
})

// ── Hidden records ────────────────────────────────────────────────────────────

describe('cpd.isHidden', () => {
  test('a hidden record is not claimable even when it carries time', () => {
    // True of exactly one real record ("Business Purchase Assessment 1", 15 minutes).
    // The master app marked it hidden; honouring that is the conservative reading.
    library([record({ cpd: { isHidden: true, watchedVideo: 0, reviewTemplate: 15, reheasedTemplate: 0 } })])

    expect(cpd.lookupTemplate('E.O.Y Meeting')).toBeNull()
  })

  test('a hidden duplicate can never beat the visible record', () => {
    // 21 page ids and 5 titles are duplicated in the real export, and hidden twins are
    // the commonest cause. Order must not decide the answer, so both orders are pinned.
    const visible = record({ cpd: { isHidden: false, watchedVideo: 7, reviewTemplate: 30, reheasedTemplate: 20 } })
    const hiddenTwin = record({ cpd: { isHidden: true, watchedVideo: 0, reviewTemplate: 0, reheasedTemplate: 0 } })

    library([hiddenTwin, visible])
    expect(cpd.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(57)

    library([visible, hiddenTwin])
    expect(cpd.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(57)
  })

  test('isHidden must be exactly true to hide a record', () => {
    library([record({ cpd: { isHidden: 'yes', watchedVideo: 9, reviewTemplate: 0, reheasedTemplate: 0 } })])

    expect(cpd.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(9)
  })
})

// ── Collisions between two visible records ────────────────────────────────────

describe('duplicate titles', () => {
  test('a record carrying time beats an all-zero one, whichever comes first', () => {
    const zero = record({ cpd: { isHidden: false, watchedVideo: 0, reviewTemplate: 0, reheasedTemplate: 0 } })
    const real = record({ cpd: { isHidden: false, watchedVideo: 5, reviewTemplate: 20, reheasedTemplate: 45 } })

    library([zero, real])
    expect(cpd.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(70)

    library([real, zero])
    expect(cpd.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(70)
  })

  test('when both carry time the LOWER total wins — never over-claim on a data defect', () => {
    const lower = record({ cpd: { isHidden: false, watchedVideo: 24, reviewTemplate: 30, reheasedTemplate: 30 } })
    const higher = record({ cpd: { isHidden: false, watchedVideo: 30, reviewTemplate: 90, reheasedTemplate: 0 } })

    library([lower, higher])
    expect(cpd.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(84)

    library([higher, lower])
    expect(cpd.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(84)
  })

  test('a disagreement is logged, naming the template and both figures', () => {
    // No silent parking: the export defect has to be reconcilable, not absorbed.
    library([
      record({ cpd: { isHidden: false, watchedVideo: 24, reviewTemplate: 30, reheasedTemplate: 30 } }),
      record({ cpd: { isHidden: false, watchedVideo: 30, reviewTemplate: 90, reheasedTemplate: 0 } })
    ])

    cpd.lookupTemplate('E.O.Y Meeting')

    expect(warn).toHaveBeenCalledTimes(1)
    const message = warn.mock.calls[0][0]
    expect(message).toContain('E.O.Y Meeting')
    expect(message).toContain('84')
    expect(message).toContain('120')
  })

  test('two records that AGREE are not logged as a disagreement', () => {
    library([record(), record({ page: 'id-2' })])

    cpd.lookupTemplate('E.O.Y Meeting')

    expect(warn).not.toHaveBeenCalled()
  })
})

// ── Names ─────────────────────────────────────────────────────────────────────

describe('matching a stored template name', () => {
  test.each([
    ['the exact title', 'E.O.Y Meeting'],
    ['lowercased, as recommended_templates stores it', 'e.o.y meeting'],
    ['padded with whitespace', '  E.O.Y Meeting  '],
    ['with collapsed inner spacing', 'E.O.Y   Meeting'],
    ['shouted', 'E.O.Y MEETING']
  ])('matches %s', (_label, name) => {
    library([record()])

    expect(cpd.lookupTemplate(name).title).toBe('E.O.Y Meeting')
  })

  test.each([
    ['an unknown name', 'Not A Template'],
    ['an empty string', ''],
    ['whitespace only', '   '],
    ['a number', 42],
    ['null', null],
    ['undefined', undefined],
    ['an object', {}]
  ])('%s finds nothing', (_label, name) => {
    library([record()])

    expect(cpd.lookupTemplate(name)).toBeNull()
  })

  test('a record with no usable title is skipped rather than indexed under nothing', () => {
    library([record({ title: '   ' }), record({ page: 'id-2', title: 'Loan Estimator' })])

    expect(cpd.lookupTemplate('Loan Estimator').totalMinutes).toBe(99)
    expect(cpd.lookupTemplate('')).toBeNull()
  })

  test('normaliseTitle is the one rule both sides use', () => {
    expect(cpd.normaliseTitle('  E.O.Y   Meeting ')).toBe('e.o.y meeting')
    expect(cpd.normaliseTitle(null)).toBe('')
  })
})

// ── The index is not mutable from outside ─────────────────────────────────────

describe('the cached index', () => {
  test('a caller cannot corrupt the catalogue through the entry it is handed', () => {
    library([record()])

    const first = cpd.lookupTemplate('E.O.Y Meeting')
    first.activities[0].minutes = 9999
    first.title = 'tampered'

    expect(cpd.lookupTemplate('E.O.Y Meeting').activities[0].minutes).toBe(9)
    expect(cpd.lookupTemplate('E.O.Y Meeting').title).toBe('E.O.Y Meeting')
  })

  test('is built once and reused until reset', () => {
    library([record()])

    cpd.lookupTemplate('E.O.Y Meeting')
    cpd.lookupTemplate('E.O.Y Meeting')

    expect(getOrgTemplates).toHaveBeenCalledTimes(1)
  })

  test('resetCache picks up a new export', () => {
    library([record()])
    expect(cpd.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(99)

    library([record({ cpd: { isHidden: false, watchedVideo: 5, reviewTemplate: 0, reheasedTemplate: 0 } })])
    expect(cpd.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(5)
  })
})

// ── claimableFor ──────────────────────────────────────────────────────────────

describe('claimableFor', () => {
  test('collapses a template used in several sessions to ONE entry', () => {
    // Three uses of one template is one template with three claimable activities —
    // not three templates. How many TIMES each may be claimed is a separate question,
    // and deliberately unbounded (owner ruling 2026-07-29).
    library([record()])

    const out = cpd.claimableFor(['E.O.Y Meeting', 'e.o.y meeting', '  E.O.Y  Meeting '])

    expect(out).toHaveLength(1)
    expect(out[0].title).toBe('E.O.Y Meeting')
  })

  test('drops names the catalogue does not offer, keeping the rest', () => {
    library([record(), record({ page: 'id-2', title: 'Loan Estimator' })])

    const out = cpd.claimableFor(['Not A Template', 'Loan Estimator', '', null, 'E.O.Y Meeting'])

    expect(out.map(e => e.title)).toEqual(['Loan Estimator', 'E.O.Y Meeting'])
  })

  test.each([
    ['a non-array', 'E.O.Y Meeting'],
    ['null', null],
    ['undefined', undefined]
  ])('%s yields an empty list rather than throwing', (_label, value) => {
    library([record()])

    expect(cpd.claimableFor(value)).toEqual([])
  })
})

// ── resolveClaim — where a claim's value is actually decided ───────────────────

describe('resolveClaim', () => {
  test('returns the stored shape: real title, page, minutes and pledge', () => {
    library([record()])

    expect(cpd.resolveClaim('e.o.y meeting', 'rehearsal')).toEqual({
      title: 'E.O.Y Meeting',
      page: 'id-1',
      activity: 'rehearsal',
      minutes: 30,
      pledgeKey: 'cpd.pledge.rehearsal',
      pledgeVersion: 1
    })
  })

  test('a template with no page id resolves without one rather than inventing a link', () => {
    library([record({ page: '   ' })])

    expect(cpd.resolveClaim('E.O.Y Meeting', 'video').page).toBeNull()
  })

  test('refuses an activity the template carries no time for', () => {
    library([record({ cpd: { isHidden: false, watchedVideo: 9, reviewTemplate: 0, reheasedTemplate: 0 } })])

    expect(cpd.resolveClaim('E.O.Y Meeting', 'reading')).toBeNull()
  })

  test.each([
    ['an unknown activity', 'sleeping'],
    ['the right word in the wrong case', 'Video'],
    ['an empty string', ''],
    ['a number', 1],
    ['null', null],
    ['undefined', undefined]
  ])('refuses %s', (_label, activity) => {
    library([record()])

    expect(cpd.resolveClaim('E.O.Y Meeting', activity)).toBeNull()
  })

  test('refuses a template the catalogue does not know', () => {
    library([record()])

    expect(cpd.resolveClaim('Invented Template', 'video')).toBeNull()
  })
})

// ── normaliseClaimRequest — the only two values a client supplies ──────────────

describe('normaliseClaimRequest', () => {
  test('accepts and trims a well-formed request', () => {
    expect(cpd.normaliseClaimRequest({ templateTitle: '  E.O.Y Meeting  ', activity: 'video' }))
      .toEqual({ templateTitle: 'E.O.Y Meeting', activity: 'video' })
  })

  test('trims the activity too', () => {
    expect(cpd.normaliseClaimRequest({ templateTitle: 'X', activity: ' reading ' }).activity)
      .toBe('reading')
  })

  test('ignores anything else the client sends', () => {
    // Nothing that gives a claim its value may arrive from the browser: a request
    // naming its own minutes must not carry them through.
    const out = cpd.normaliseClaimRequest({
      templateTitle: 'E.O.Y Meeting',
      activity: 'video',
      minutes: 9999,
      advisorId: 'someone-else',
      claimedAt: '1999-01-01'
    })

    expect(out).toEqual({ templateTitle: 'E.O.Y Meeting', activity: 'video' })
  })

  test('refuses a title longer than the column can hold', () => {
    const tooLong = 'x'.repeat(cpd.MAX_TITLE_LENGTH + 1)

    expect(cpd.normaliseClaimRequest({ templateTitle: tooLong, activity: 'video' })).toBeNull()
  })

  test('accepts a title exactly at the limit', () => {
    const atLimit = 'x'.repeat(cpd.MAX_TITLE_LENGTH)

    expect(cpd.normaliseClaimRequest({ templateTitle: atLimit, activity: 'video' }).templateTitle)
      .toHaveLength(cpd.MAX_TITLE_LENGTH)
  })

  test.each([
    ['no body', undefined],
    ['null', null],
    ['a string', 'E.O.Y Meeting'],
    ['an array', ['E.O.Y Meeting', 'video']],
    ['no title', { activity: 'video' }],
    ['an empty title', { templateTitle: '   ', activity: 'video' }],
    ['a non-string title', { templateTitle: 42, activity: 'video' }],
    ['no activity', { templateTitle: 'E.O.Y Meeting' }],
    ['an unknown activity', { templateTitle: 'E.O.Y Meeting', activity: 'napping' }],
    ['a non-string activity', { templateTitle: 'E.O.Y Meeting', activity: 3 }]
  ])('refuses %s', (_label, body) => {
    expect(cpd.normaliseClaimRequest(body)).toBeNull()
  })
})

// ── CPD follows the library in force — item 4.56, Mike's ruling 2026-09-01 ────
// Recommendations come from whichever library a firm's tier chain has uploaded, so
// claimable CPD must be priced from the SAME library. Every rule above — hidden
// records, the lower-figure collision rule, rounding — applies to a firm's library
// identically, because the same index build runs over it.

describe('catalogueForLibrary — a firm library replaces the seed wholesale', () => {
  const firmRecord = over => Object.assign({
    page: 'firm-1',
    title: 'E.O.Y Meeting',
    cpd: { isHidden: false, watchedVideo: 4, reviewTemplate: 20, reheasedTemplate: 0 }
  }, over)

  test('the firm\'s minutes win for a title both libraries carry', () => {
    library([record()]) // seed: 99 minutes

    const firm = cpd.catalogueForLibrary([firmRecord()])

    expect(firm.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(24)
    expect(firm.lookupTemplate('E.O.Y Meeting').page).toBe('firm-1')
  })

  test('a seed-only title is NOT claimable under a firm library — wholesale, never merged', () => {
    library([record(), record({ page: 'id-2', title: 'Loan Estimator' })])

    const firm = cpd.catalogueForLibrary([firmRecord()])

    expect(firm.lookupTemplate('Loan Estimator')).toBeNull()
    // The module-level lookup is still the platform view, untouched by the firm's.
    expect(cpd.lookupTemplate('Loan Estimator').totalMinutes).toBe(99)
  })

  test('a firm-only title IS claimable under the firm library', () => {
    library([record()])

    const firm = cpd.catalogueForLibrary([firmRecord({ title: 'Firm Special' })])

    expect(firm.lookupTemplate('Firm Special').totalMinutes).toBe(24)
    expect(cpd.lookupTemplate('Firm Special')).toBeNull()
  })

  test('the hidden-record rule applies to a firm library exactly as the seed', () => {
    library([record()])

    const firm = cpd.catalogueForLibrary([
      firmRecord({ cpd: { isHidden: true, watchedVideo: 4, reviewTemplate: 20, reheasedTemplate: 0 } })
    ])

    expect(firm.lookupTemplate('E.O.Y Meeting')).toBeNull()
  })

  test('the never-over-claim collision rule applies within a firm library, and is logged', () => {
    library([record()])

    const firm = cpd.catalogueForLibrary([
      firmRecord({ cpd: { isHidden: false, watchedVideo: 24, reviewTemplate: 30, reheasedTemplate: 30 } }),
      firmRecord({ page: 'firm-2', cpd: { isHidden: false, watchedVideo: 30, reviewTemplate: 90, reheasedTemplate: 0 } })
    ])

    expect(firm.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(84)
    expect(warn).toHaveBeenCalledTimes(1)
  })

  test.each([
    ['null', null],
    ['undefined', undefined],
    ['an empty array', []],
    ['a non-array', 'not a library']
  ])('%s binds to the platform seed — no library in force', (_label, value) => {
    library([record()])

    expect(cpd.catalogueForLibrary(value).lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(99)
  })

  test('resolveClaim through the firm catalogue returns the firm\'s stored values', () => {
    library([record()])

    const firm = cpd.catalogueForLibrary([firmRecord()])

    expect(firm.resolveClaim('e.o.y meeting', 'video')).toEqual({
      title: 'E.O.Y Meeting',
      page: 'firm-1',
      activity: 'video',
      minutes: 4,
      pledgeKey: 'cpd.pledge.video',
      pledgeVersion: 1
    })
    // The seed still offers rehearsal; the firm's library does not.
    expect(firm.resolveClaim('E.O.Y Meeting', 'rehearsal')).toBeNull()
  })

  test('claimableFor through the firm catalogue prices from the firm library', () => {
    library([record()])

    const firm = cpd.catalogueForLibrary([firmRecord()])
    const out = firm.claimableFor(['E.O.Y Meeting', 'Not A Template'])

    expect(out).toHaveLength(1)
    expect(out[0].totalMinutes).toBe(24)
  })

  test('one index per library array — cached by the array itself, dropped on resetCache', () => {
    library([record()])
    const firmLibrary = [firmRecord()]

    expect(cpd.catalogueForLibrary(firmLibrary).lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(24)

    // A mutation after the first build is not seen — the index is cached against
    // this array, the way templateLibrary hands the same array back until its TTL.
    firmLibrary.push(firmRecord({ page: 'firm-2', title: 'Firm Special' }))
    expect(cpd.catalogueForLibrary(firmLibrary).lookupTemplate('Firm Special')).toBeNull()

    // resetCache drops it, as it does the seed index.
    cpd.resetCache()
    expect(cpd.catalogueForLibrary(firmLibrary).lookupTemplate('Firm Special').totalMinutes).toBe(24)
  })
})

describe('catalogueFor — the scoped entry point the CPD routes use', () => {
  test('asks templateLibrary which library is in force for the scope', async () => {
    library([record()])

    await cpd.catalogueFor('firm-123')

    expect(loadEffectiveTemplates).toHaveBeenCalledWith('firm-123')
  })

  test('prices from the resolved library', async () => {
    library([record()])
    loadEffectiveTemplates.mockResolvedValue([{
      page: 'firm-1',
      title: 'E.O.Y Meeting',
      cpd: { isHidden: false, watchedVideo: 4, reviewTemplate: 20, reheasedTemplate: 0 }
    }])

    const firm = await cpd.catalogueFor('firm-123')

    expect(firm.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(24)
  })

  test('null — no tier has uploaded — is exactly the platform seed', async () => {
    library([record()])
    loadEffectiveTemplates.mockResolvedValue(null)

    const scoped = await cpd.catalogueFor('firm-123')

    expect(scoped.lookupTemplate('E.O.Y Meeting').totalMinutes).toBe(99)
  })
})
