'use strict'

/**
 * @file Item 4.49 — the acronym expansions the AI is given must match the firm's own
 * source documents.
 *
 * 🔴 WHY THIS PINS WORDING, WHEN THE HOUSE RULE NORMALLY FORBIDS IT.
 * CLAUDE.md allows exactly this case: *"Where wording genuinely must not drift — the
 * master app's own transcribed content, a regulatory phrase — pin it in ONE test next
 * to the data it protects, and say in a comment why that string is load-bearing."*
 * Each string below is load-bearing because it is a SPECIFIC, PLAUSIBLE, AUTHORITATIVE
 * claim about the firm's own IP. Nobody in UAT can tell a right expansion from a wrong
 * one by looking — that is precisely how the fabricated A.I.D.C.R.A expansion survived
 * from the day the summaries were drafted until 2026-07-31, reaching the AI on every
 * sales-marketing conversation in between.
 *
 * WHAT THIS TEST IS NOT. It does not prove the summaries are free of invention — only
 * that these seventeen high-risk claims still say what their sources say. The sweep that
 * produced the list is recorded on `features/to-do-done-and-parked.md` under 4.49.
 *
 * HOW EACH WAS VERIFIED (2026-08-26): every PDF in `Domain Support/` was converted with
 * `pdftotext -layout` and the claim read out of the source text. The quote proving each
 * one sits in the comment beside it. The extraction is NOT part of this test — it needs
 * poppler, which is not a dependency of this project and must not become one. The test
 * compares the shipped data against the strings a human read out of the source.
 */

const { readFileSync } = require('fs')
const { resolve } = require('path')

const DATA = resolve(__dirname, '..', '..', 'data')
const read = f => readFileSync(resolve(DATA, f), 'utf8')

/**
 * Each entry: the file that must carry the claim, and the exact substring.
 * `why` records the source sentence the string was checked against.
 */
const SOURCED = [
  {
    file: 'get-team-problem-domain-support.json',
    claim: 'specific, measurable, agreed, revisable and time-bound',
    why: 'Get Team Problem Support.pdf: "A written objective must be S.M.A.R.T. (Specific, ' +
         'Measurable, Agreed, Revisable, and Time-bound)." ⚠ NOT the textbook expansion — ' +
         '"Agreed" and "Revisable" are the firm\'s own, and the template itself is about ' +
         'the "correct" use of the acronym. Anyone "correcting" this to Achievable/Relevant ' +
         'would be overwriting the IP with a generic version, which is why it is pinned.'
  },
  {
    file: 'get-seminar-domain-support.json',
    claim: 'Concept, Principle, Detail',
    why: 'Get Seminar Support.pdf: "What is the C.P.D hierarchy? Concept - Principle - ' +
         'Detail." This file read "Principles" until 2026-08-26 — the one discrepancy the ' +
         '4.49 sweep found in seventeen claims. Singular, as the source has it, and as ' +
         'sales-marketing and the master export both already had it.'
  },
  {
    file: 'sales-marketing-domain-support.json',
    claim: 'Concept, Principle, Detail',
    why: 'Same source hierarchy, stated in the sales-marketing file. Already correct; ' +
         'pinned so the two files cannot drift apart from each other again.'
  },
  {
    file: 'sales-marketing-domain-support.json',
    claim: 'Attention, Interest, Desire, Credibility, Risk Removal, Action',
    why: 'Sales & Marketing Support.pdf, A.I.D.C.R.A Model. 🔴 THIS IS THE ORIGINAL DEFECT. ' +
         'It read "Attention, Interest, Desire, Conviction, Response, Action" — invented ' +
         'when the summary was drafted, ruled AI-generated by Mike on 2026-07-31 and ' +
         'corrected by him the same day. It is the reason item 4.49 exists.'
  },
  {
    file: 'get-seminar-domain-support.json',
    claim: 'Survival, Security, Acceptance, Recognition or Contribution',
    why: 'Get Seminar Support.pdf: "relevance by linking your concept to their key values: ' +
         'Survival, Security, Acceptance, Recognition, or Contribution (W.I.I.F.M)." The ' +
         'acronym labels the values list here — it is not being expanded as words, which ' +
         'is unusual enough that a later reader might "fix" it.'
  },
  {
    file: 'governance-domain-support.json',
    claim: 'White for missing information',
    why: 'Governance & Leadership support.pdf: "White (information missing), Red ' +
         '(feelings/intuition), Black (caution/devil\'s advocate), Yellow (objective ' +
         'benefits), Green (creative alternatives), and Blue (sequencing/organizing)."'
  },
  {
    file: 'strategy-domain-support.json',
    claim: 'One Night Stand',
    why: 'Strategic Planning Support.pdf: "one of 4 stages: One Night Stand (singular ' +
         'contract/project), Dating (ongoing...)" — the Business Dating ladder, ' +
         'One Night Stand / Dating / Engaged / Married.'
  }
]

describe('acronym and framework expansions still match the firm\'s source documents', () => {
  test.each(SOURCED.map(s => [`${s.file} — ${s.claim.slice(0, 46)}`, s]))(
    '%s', (_label, s) => {
      expect(read(s.file)).toContain(s.claim)
    }
  )

  // 🔴 THE NEGATIVE CASE, AND IT IS THE ONE THAT MATTERS. A test that only checks the
  // right string is present passes just as happily when the wrong one is present too —
  // and the A.I.D.C.R.A defect was a wrong string sitting where a right one belonged.
  test('the invented A.I.D.C.R.A expansion has not come back', () => {
    expect(read('sales-marketing-domain-support.json')).not.toMatch(/Conviction, Response/i)
  })

  test('the C.P.D hierarchy is not pluralised anywhere in the domain-support data', () => {
    const { readdirSync } = require('fs')
    const files = readdirSync(DATA).filter(f => /domain-support\.json$/.test(f))
    const offenders = files.filter(f => /Concept, Principles, Detail/.test(read(f)))
    expect(offenders).toEqual([])
  })
})
