'use strict'

/**
 * Sheet row -> the path in the Three-Way Forecast model's payload that carries it.
 *
 * Shared by the year-1 golden test and the three-year chain test, because it is ONE
 * mapping and two copies would drift. Not a test file itself (no `.test.` suffix), so
 * jest does not pick it up.
 *
 * IT IS ALSO THE PORT'S DOCUMENTATION: row by row, it says what each part of
 * `3 way Filter.xlsx` became. Rows up to 104 sit on the same row in all three year
 * sheets; from 106 up, years 2 and 3 are ONE ROW HIGHER, because year 1 carries a blank
 * row the later sheets drop. Verified across all 290 rows on both later sheets.
 */
const SOURCE_ROWS = {
  // --- Forecast Statement of Financial Performance ---
  6: 'profitAndLoss.revenue',
  9: 'profitAndLoss.openingInventory',
  10: 'profitAndLoss.freight',
  11: 'profitAndLoss.otherDirectExpensesExempt',
  12: 'profitAndLoss.otherDirectTwo',
  13: 'profitAndLoss.commissions',
  14: 'profitAndLoss.purchases',
  15: 'profitAndLoss.costOfSalesSubtotal',
  16: 'profitAndLoss.closingInventory',
  17: 'profitAndLoss.costOfSales',
  19: 'profitAndLoss.grossSurplus',
  20: 'profitAndLoss.grossMargin',
  23: 'profitAndLoss.overheads.accLevies',
  24: 'profitAndLoss.overheads.accountancy',
  25: 'profitAndLoss.overheads.advertising',
  26: 'profitAndLoss.overheads.bankCharges',
  27: 'profitAndLoss.overheads.computerExpenses',
  28: 'profitAndLoss.depreciation',
  29: 'profitAndLoss.overheads.generalExpenses',
  30: 'profitAndLoss.overheads.insurance',
  31: 'profitAndLoss.interestBankOverdraft',
  32: 'profitAndLoss.interestTermLoans',
  33: 'profitAndLoss.overheads.interestIrd',
  34: 'profitAndLoss.overheads.occupancy',
  35: 'profitAndLoss.overheads.power',
  36: 'profitAndLoss.overheads.printing',
  37: 'profitAndLoss.overheads.rent',
  38: 'profitAndLoss.overheads.repairs',
  39: 'profitAndLoss.overheads.shareholderSalaries',
  40: 'profitAndLoss.overheads.subscriptions',
  41: 'profitAndLoss.overheads.telephone',
  42: 'profitAndLoss.overheads.vehicle',
  43: 'profitAndLoss.overheads.wages',
  44: 'profitAndLoss.overheads.otherOne',
  45: 'profitAndLoss.overheads.otherTwo',
  46: 'profitAndLoss.overheads.otherThree',
  47: 'profitAndLoss.overheads.otherFour',
  48: 'profitAndLoss.overheads.otherFive',
  49: 'profitAndLoss.totalOverheads',
  51: 'profitAndLoss.operatingSurplus',
  53: 'profitAndLoss.interestIncomeBank',
  54: 'profitAndLoss.interestIncomeShareholders',
  55: 'profitAndLoss.otherIncomeGstInclusive',
  56: 'profitAndLoss.otherIncomeGstExempt',
  57: 'profitAndLoss.totalOtherIncome',
  59: 'profitAndLoss.netSurplusBeforeTax',
  61: 'profitAndLoss.taxProvision',
  63: 'profitAndLoss.netSurplusAfterTax',
  64: 'profitAndLoss.netMargin',

  // --- Forecast Statement of Financial Position ---
  70: 'balanceSheet.months.authorisedCapital',
  71: 'balanceSheet.months.capitalGain',
  72: 'balanceSheet.months.retainedEarnings',
  73: 'balanceSheet.months.totalEquity',
  76: 'balanceSheet.months.cashAtBank',
  77: 'balanceSheet.months.accountsReceivable',
  78: 'balanceSheet.months.inventory',
  79: 'balanceSheet.months.incomeTaxAsset',
  80: 'balanceSheet.months.gstRefund',
  81: 'balanceSheet.months.prepayments',
  82: 'balanceSheet.months.shareholderCurrentAssets',
  83: 'balanceSheet.months.otherCurrentAsset',
  84: 'balanceSheet.months.totalCurrentAssets',
  87: 'balanceSheet.months.bankOverdraft',
  88: 'balanceSheet.months.accountsPayable',
  89: 'balanceSheet.months.incomeTaxLiability',
  90: 'balanceSheet.months.gstPayable',
  91: 'balanceSheet.months.accruedExpenses',
  92: 'balanceSheet.months.shareholderCurrentLiabilities',
  93: 'balanceSheet.months.otherCurrentLiability',
  94: 'balanceSheet.months.totalCurrentLiabilities',
  96: 'balanceSheet.months.workingCapital',
  99: 'balanceSheet.months.nonCurrentAssets.vehicles',
  100: 'balanceSheet.months.nonCurrentAssets.leaseholdImprovements',
  101: 'balanceSheet.months.nonCurrentAssets.plantEquipment',
  102: 'balanceSheet.months.nonCurrentAssets.officeEquipment',
  103: 'balanceSheet.months.nonCurrentAssets.computerHardware',
  104: 'balanceSheet.months.nonCurrentAssets.other',
  106: 'balanceSheet.months.totalNonCurrentAssets',
  109: 'balanceSheet.months.nonCurrentLiabilities.0.balance',
  110: 'balanceSheet.months.nonCurrentLiabilities.1.balance',
  111: 'balanceSheet.months.nonCurrentLiabilities.2.balance',
  112: 'balanceSheet.months.otherNonCurrentLiability',
  113: 'balanceSheet.months.totalNonCurrentLiabilities',
  115: 'balanceSheet.months.netAssets',
  116: 'balanceSheet.months.balanceCheck',

  // --- Forecast Statement of Cashflows ---
  122: 'cashFlow.receipts.fromDebtors',
  123: 'cashFlow.receipts.interestReceived',
  124: 'cashFlow.receipts.loanDrawdowns',
  125: 'cashFlow.receipts.gstRefunds',
  126: 'cashFlow.receipts.taxRefunds',
  127: 'cashFlow.receipts.otherIncomeGstInclusive',
  128: 'cashFlow.receipts.otherIncomeGstExempt',
  129: 'cashFlow.receipts.shareholderAdvances',
  130: 'cashFlow.receipts.assetSales',
  131: 'cashFlow.totalReceipts',
  134: 'cashFlow.payments.accountsPayable',
  135: 'cashFlow.payments.currentMonthGstInclusive',
  136: 'cashFlow.payments.currentMonthGstFree',
  137: 'cashFlow.payments.interestPaid',
  138: 'cashFlow.payments.loanPrincipal',
  139: 'cashFlow.payments.gstPaid',
  140: 'cashFlow.payments.taxPaid',
  141: 'cashFlow.payments.shareholderDrawings',
  142: 'cashFlow.payments.capitalExpenditure',
  143: 'cashFlow.totalPayments',
  145: 'cashFlow.netMovement',
  147: 'cashFlow.openingBalance',
  149: 'cashFlow.closingBalance',
  151: 'cashFlow.overdraftInterest',
  152: 'cashFlow.inFundsInterest',

  // --- Accounts Receivable ---
  157: 'schedules.debtors.sales',
  158: 'schedules.debtors.gst',
  159: 'schedules.debtors.inclusive',
  163: 'schedules.debtors.collectionSlices.0',
  164: 'schedules.debtors.collectionSlices.1',
  165: 'schedules.debtors.collectionSlices.2',
  166: 'schedules.debtors.collectionSlices.3',
  167: 'schedules.debtors.collectionSlices.4',
  168: 'schedules.debtors.openingBalanceRunOff',
  169: 'schedules.debtors.cashReceived',
  173: 'schedules.debtors.openingBalance',
  174: 'schedules.debtors.inclusive',
  175: 'schedules.debtors.subtotal',
  176: 'schedules.debtors.cashReceived',
  177: 'schedules.debtors.closingBalance',

  // --- Expense payments. Each row copies a P&L line; the mapping IS the port's
  //     statement of which block settles which cost, and it is what R6/R7 corrected.
  183: 'schedules.accruals.accLeviesPaid',
  184: 'profitAndLoss.overheads.accountancy',
  185: 'profitAndLoss.overheads.advertising',
  186: 'profitAndLoss.overheads.computerExpenses',
  187: 'profitAndLoss.freight',
  188: 'profitAndLoss.overheads.generalExpenses',
  189: 'schedules.accruals.insurancePaid',
  190: 'profitAndLoss.overheads.occupancy',
  191: 'profitAndLoss.overheads.power',
  192: 'profitAndLoss.overheads.printing',
  193: 'profitAndLoss.overheads.repairs',
  194: 'profitAndLoss.overheads.subscriptions',
  195: 'profitAndLoss.overheads.telephone',
  196: 'profitAndLoss.overheads.vehicle',
  197: 'profitAndLoss.overheads.otherOne',
  198: 'profitAndLoss.overheads.otherTwo',
  199: 'profitAndLoss.overheads.otherThree',
  200: 'profitAndLoss.overheads.otherFour',
  202: 'schedules.expensePayments.blockOneNet',
  203: 'schedules.expensePayments.blockOneGst',
  204: 'schedules.expensePayments.blockOneGross',
  208: 'profitAndLoss.overheads.rent',
  209: 'schedules.expensePayments.blockTwoNet',
  210: 'schedules.expensePayments.blockTwoGst',
  211: 'schedules.expensePayments.blockTwoGross',
  215: 'profitAndLoss.overheads.bankCharges',
  216: 'profitAndLoss.commissions',
  217: 'profitAndLoss.overheads.otherFive',
  218: 'profitAndLoss.otherDirectTwo',
  219: 'profitAndLoss.overheads.shareholderSalaries',
  220: 'profitAndLoss.overheads.wages',
  221: 'schedules.expensePayments.blockThreeTotal',

  // --- Inventory purchases and Accounts Payable ---
  225: 'schedules.inventory.purchases',
  226: 'schedules.creditors.gst',
  227: 'schedules.creditors.inclusive',
  229: 'schedules.creditors.paymentSlices.0',
  230: 'schedules.creditors.paymentSlices.1',
  231: 'schedules.creditors.paymentSlices.2',
  232: 'schedules.creditors.paymentSlices.3',
  233: 'schedules.creditors.paymentSlices.4',
  234: 'schedules.creditors.paid',
  238: 'schedules.creditors.openingBalance',
  239: 'schedules.expensePayments.blockOneGross',
  240: 'schedules.creditors.inclusive',
  241: 'schedules.creditors.subtotal',
  242: 'schedules.creditors.overheadsPaid',
  243: 'schedules.creditors.paid',
  244: 'schedules.creditors.openingBalanceRunOff',
  245: 'schedules.creditors.closingBalance',

  // --- Inventory ---
  250: 'schedules.inventory.openingInventory',
  251: 'schedules.inventory.purchases',
  252: 'schedules.inventory.subtotal',
  253: 'schedules.inventory.costOfSales',
  254: 'schedules.inventory.closingInventory',

  // --- Term loans / hire purchase ---
  263: 'schedules.loans.0.openingBalance',
  264: 'schedules.loans.0.drawdowns',
  265: 'schedules.loans.0.capitalRepaid',
  266: 'schedules.loans.0.lumpSumRepayments',
  267: 'schedules.loans.0.closingBalance',
  269: 'schedules.loans.0.interest',
  276: 'schedules.loans.1.openingBalance',
  277: 'schedules.loans.1.drawdowns',
  278: 'schedules.loans.1.capitalRepaid',
  279: 'schedules.loans.1.lumpSumRepayments',
  280: 'schedules.loans.1.closingBalance',
  282: 'schedules.loans.1.interest',
  289: 'schedules.loans.2.openingBalance',
  290: 'schedules.loans.2.drawdowns',
  291: 'schedules.loans.2.capitalRepaid',
  292: 'schedules.loans.2.lumpSumRepayments',
  293: 'schedules.loans.2.closingBalance',
  295: 'schedules.loans.2.interest',

  // --- Fixed assets, all six categories ---
  302: 'schedules.assets.0.bookValue',
  303: 'schedules.assets.0.additions',
  304: 'schedules.assets.0.disposals',
  305: 'schedules.assets.0.subtotal',
  306: 'schedules.assets.0.depreciation',
  307: 'schedules.assets.0.closingValue',
  312: 'schedules.assets.1.bookValue',
  313: 'schedules.assets.1.additions',
  314: 'schedules.assets.1.disposals',
  315: 'schedules.assets.1.subtotal',
  316: 'schedules.assets.1.depreciation',
  317: 'schedules.assets.1.closingValue',
  322: 'schedules.assets.2.bookValue',
  323: 'schedules.assets.2.additions',
  324: 'schedules.assets.2.disposals',
  325: 'schedules.assets.2.subtotal',
  326: 'schedules.assets.2.depreciation',
  327: 'schedules.assets.2.closingValue',
  332: 'schedules.assets.3.bookValue',
  333: 'schedules.assets.3.additions',
  334: 'schedules.assets.3.disposals',
  335: 'schedules.assets.3.subtotal',
  336: 'schedules.assets.3.depreciation',
  337: 'schedules.assets.3.closingValue',
  342: 'schedules.assets.4.bookValue',
  343: 'schedules.assets.4.additions',
  344: 'schedules.assets.4.disposals',
  345: 'schedules.assets.4.subtotal',
  346: 'schedules.assets.4.depreciation',
  347: 'schedules.assets.4.closingValue',
  352: 'schedules.assets.5.bookValue',
  353: 'schedules.assets.5.additions',
  354: 'schedules.assets.5.disposals',
  355: 'schedules.assets.5.subtotal',
  356: 'schedules.assets.5.depreciation',
  357: 'schedules.assets.5.closingValue',

  // --- Shareholder current accounts ---
  363: 'schedules.shareholders.0.openingBalance',
  364: 'schedules.shareholders.0.advances',
  365: 'schedules.shareholders.0.drawings',
  366: 'schedules.shareholders.0.interestOnOverdrawn',
  367: 'schedules.shareholders.0.closingBalance',
  370: 'schedules.shareholders.1.openingBalance',
  371: 'schedules.shareholders.1.advances',
  372: 'schedules.shareholders.1.drawings',
  373: 'schedules.shareholders.1.interestOnOverdrawn',
  374: 'schedules.shareholders.1.closingBalance',
  377: 'schedules.shareholders.2.openingBalance',
  378: 'schedules.shareholders.2.advances',
  379: 'schedules.shareholders.2.drawings',
  380: 'schedules.shareholders.2.interestOnOverdrawn',
  381: 'schedules.shareholders.2.closingBalance',
  384: 'schedules.shareholders.3.openingBalance',
  385: 'schedules.shareholders.3.advances',
  386: 'schedules.shareholders.3.drawings',
  387: 'schedules.shareholders.3.interestOnOverdrawn',
  388: 'schedules.shareholders.3.closingBalance',

  // --- Goods and Services Tax ---
  397: 'schedules.gst.onIncome',
  398: 'schedules.gst.onOtherIncome',
  399: 'schedules.gst.onAssetSales',
  400: 'schedules.gst.outputs',
  402: 'schedules.gst.onExpenses',
  403: 'schedules.gst.onAssetPurchases',
  404: 'schedules.gst.inputs',
  406: 'schedules.gst.forMonth',
  409: 'schedules.gst.fileOneMonthly',
  410: 'schedules.gst.fileTwoMonthly',
  411: 'schedules.gst.fileSixMonthly',
  413: 'schedules.gst.amountToFile',
  416: 'schedules.gst.balanceOpening',
  417: 'schedules.debtors.gst',
  418: 'schedules.gst.onOtherIncome',
  419: 'schedules.gst.onAssetSales',
  420: 'schedules.gst.balanceSubtotal',
  421: 'schedules.gst.onPayables',
  422: 'schedules.gst.onAssetPurchases',
  423: 'schedules.gst.paymentsMade',
  424: 'schedules.gst.balanceClosing',

  // --- Prepayments / accrued expenses ---
  429: 'schedules.accruals.openingBalance',
  430: 'schedules.accruals.accLevies',
  431: 'schedules.accruals.insurance',
  432: 'schedules.accruals.subtotal',
  433: 'schedules.accruals.accLeviesPaid',
  434: 'schedules.accruals.insurancePaid',
  435: 'schedules.accruals.closingBalance',

  // --- Provision for tax ---
  440: 'schedules.tax.lossesBroughtForward',
  441: 'schedules.tax.taxOnMonthProfit',
  442: 'schedules.tax.lossesUtilised',
  443: 'schedules.tax.lossesCarriedForward',
  445: 'schedules.tax.openingBalance',
  446: 'schedules.tax.provision',
  447: 'schedules.tax.payments',
  448: 'schedules.tax.refunds',
  449: 'schedules.tax.closingBalance'
}

module.exports = { SOURCE_ROWS }
